version: "3.9"
services:
  sdkgen:
    build:
      context: .
      dockerfile: sdk-build/Dockerfile
    volumes:
      - .:/workspace   # mount repo for in-place regen
    environment:
      - OPENAPI_PATH=schemas/openapi.json
      - OUT_DIR=sdk-output
      - VALIDATE_SPEC=true
      - GENERATE_TYPESCRIPT=true
      - GENERATE_PYTHON=true
      - GENERATE_GRAPHQL=true
  
  # Service for running the generated SDK tests
  sdktest:
    build:
      context: .
      dockerfile: sdk-build/Dockerfile
    volumes:
      - .:/workspace
    command: ["python", "-m", "pytest", "tests/sdk"]
    depends_on:
      - sdkgen
