version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9090:9090"
    environment:
      - SIM_ENV=development
      - SIM_DEBUG=true
      - SIM_RELOAD=true
      - SIM_FEATURES=ENABLE_PROMETHEUS,ENABLE_DEBUG_LOGGING
      - SIM_DB_HOST=db
      - SIM_DB_PORT=5432
      - SIM_DB_NAME=sim
      - SIM_DB_USER=sim
      - SIM_DB_PASSWORD=sim
      - DB_URL=postgresql+asyncpg://sim:sim@db:5432/sim
      - USE_S3=false
      - S3_ENDPOINT=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - S3_BUCKET=simulation-results
    volumes:
      - ./:/app
      - ./logs:/app/logs
    depends_on:
      - db
      - prometheus
      - minio

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sim
      - POSTGRES_PASSWORD=sim
      - POSTGRES_DB=sim
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v2.37.0
    ports:
      - "9091:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:9.1.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  minio_data:
