# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equihome_sim_sdk.api.finance_api import FinanceApi


class TestFinanceApi(unittest.TestCase):
    """FinanceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FinanceApi()

    def tearDown(self) -> None:
        pass

    def test_calculate_cashflows_finance_cashflows_calculate_post(self) -> None:
        """Test case for calculate_cashflows_finance_cashflows_calculate_post

        Calculate Cashflows
        """
        pass

    def test_calculate_fees_finance_fees_calculate_post(self) -> None:
        """Test case for calculate_fees_finance_fees_calculate_post

        Calculate Fees
        """
        pass

    def test_get_cashflows_finance_cashflows_simulation_id_get(self) -> None:
        """Test case for get_cashflows_finance_cashflows_simulation_id_get

        Get Cashflows
        """
        pass

    def test_get_fees_finance_fees_simulation_id_get(self) -> None:
        """Test case for get_fees_finance_fees_simulation_id_get

        Get Fees
        """
        pass


if __name__ == '__main__':
    unittest.main()
