# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equihome_sim_sdk.api.tranches_api import TranchesApi


class TestTranchesApi(unittest.TestCase):
    """TranchesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TranchesApi()

    def tearDown(self) -> None:
        pass

    def test_get_coverage_test_visualization_tranches_visualization_coverage_tests_get(self) -> None:
        """Test case for get_coverage_test_visualization_tranches_visualization_coverage_tests_get

        Get Coverage Test Visualization
        """
        pass

    def test_get_coverage_tests_tranches_coverage_tests_get(self) -> None:
        """Test case for get_coverage_tests_tranches_coverage_tests_get

        Get Coverage Tests
        """
        pass

    def test_get_reserve_account_tranches_reserve_account_get(self) -> None:
        """Test case for get_reserve_account_tranches_reserve_account_get

        Get Reserve Account
        """
        pass

    def test_get_reserve_account_visualization_tranches_visualization_reserve_account_get(self) -> None:
        """Test case for get_reserve_account_visualization_tranches_visualization_reserve_account_get

        Get Reserve Account Visualization
        """
        pass

    def test_get_tranche_allocation_visualization_tranches_visualization_allocation_get(self) -> None:
        """Test case for get_tranche_allocation_visualization_tranches_visualization_allocation_get

        Get Tranche Allocation Visualization
        """
        pass

    def test_get_tranche_allocations_tranches_tranche_name_allocations_get(self) -> None:
        """Test case for get_tranche_allocations_tranches_tranche_name_allocations_get

        Get Tranche Allocations
        """
        pass

    def test_get_tranche_cashflow_visualization_tranches_visualization_cashflow_get(self) -> None:
        """Test case for get_tranche_cashflow_visualization_tranches_visualization_cashflow_get

        Get Tranche Cashflow Visualization
        """
        pass

    def test_get_tranche_cashflows_tranches_tranche_name_cashflows_get(self) -> None:
        """Test case for get_tranche_cashflows_tranches_tranche_name_cashflows_get

        Get Tranche Cashflows
        """
        pass

    def test_get_tranche_performance_visualization_tranches_visualization_performance_get(self) -> None:
        """Test case for get_tranche_performance_visualization_tranches_visualization_performance_get

        Get Tranche Performance Visualization
        """
        pass

    def test_get_tranche_waterfall_visualization_tranches_visualization_waterfall_get(self) -> None:
        """Test case for get_tranche_waterfall_visualization_tranches_visualization_waterfall_get

        Get Tranche Waterfall Visualization
        """
        pass

    def test_get_tranches_tranches_get(self) -> None:
        """Test case for get_tranches_tranches_get

        Get Tranches
        """
        pass


if __name__ == '__main__':
    unittest.main()
