# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equihome_sim_sdk.models.price_path_scenario_request import PricePathScenarioRequest

class TestPricePathScenarioRequest(unittest.TestCase):
    """PricePathScenarioRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PricePathScenarioRequest:
        """Test PricePathScenarioRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PricePathScenarioRequest`
        """
        model = PricePathScenarioRequest()
        if include_optional:
            return PricePathScenarioRequest(
                model_type = 'gbm',
                appreciation_rates = {
                    'key' : 1.337
                    },
                volatility = {
                    'key' : 1.337
                    },
                correlation_matrix = {
                    'key' : 1.337
                    },
                time_step = 'monthly',
                fund_term = 56
            )
        else:
            return PricePathScenarioRequest(
                appreciation_rates = {
                    'key' : 1.337
                    },
                volatility = {
                    'key' : 1.337
                    },
                correlation_matrix = {
                    'key' : 1.337
                    },
        )
        """

    def testPricePathScenarioRequest(self):
        """Test PricePathScenarioRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
