# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equihome_sim_sdk.models.price_path_visualization_response import PricePathVisualizationResponse

class TestPricePathVisualizationResponse(unittest.TestCase):
    """PricePathVisualizationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PricePathVisualizationResponse:
        """Test PricePathVisualizationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PricePathVisualizationResponse`
        """
        model = PricePathVisualizationResponse()
        if include_optional:
            return PricePathVisualizationResponse(
                zone_price_charts = {
                    'key' : [
                        None
                        ]
                    },
                zone_comparison_chart = [
                    None
                    ],
                suburb_price_charts = {
                    'key' : [
                        None
                        ]
                    },
                correlation_heatmap = [
                    None
                    ],
                final_distribution = {
                    'key' : [
                        None
                        ]
                    },
                cycle_position_chart = [
                    None
                    ],
                regime_chart = [
                    None
                    ]
            )
        else:
            return PricePathVisualizationResponse(
                zone_price_charts = {
                    'key' : [
                        None
                        ]
                    },
                zone_comparison_chart = [
                    None
                    ],
                suburb_price_charts = {
                    'key' : [
                        None
                        ]
                    },
                correlation_heatmap = [
                    None
                    ],
                final_distribution = {
                    'key' : [
                        None
                        ]
                    },
        )
        """

    def testPricePathVisualizationResponse(self):
        """Test PricePathVisualizationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
