# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equihome_sim_sdk.models.loan_exit_request import LoanExitRequest

class TestLoanExitRequest(unittest.TestCase):
    """LoanExitRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoanExitRequest:
        """Test LoanExitRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoanExitRequest`
        """
        model = LoanExitRequest()
        if include_optional:
            return LoanExitRequest(
                loan_id = '',
                property_id = '',
                suburb_id = '',
                zone = '',
                loan_amount = 1.337,
                property_value = 1.337,
                exit_month = 56,
                exit_type = ''
            )
        else:
            return LoanExitRequest(
                loan_id = '',
                property_id = '',
                zone = '',
                loan_amount = 1.337,
                property_value = 1.337,
                exit_month = 56,
                exit_type = '',
        )
        """

    def testLoanExitRequest(self):
        """Test LoanExitRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
