# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equihome_sim_sdk.api.exit_simulator_api import ExitSimulatorApi


class TestExitSimulatorApi(unittest.TestCase):
    """ExitSimulatorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExitSimulatorApi()

    def tearDown(self) -> None:
        pass

    def test_calculate_loan_exit_api_v1_simulations_simulation_id_exits_loan_exit_post(self) -> None:
        """Test case for calculate_loan_exit_api_v1_simulations_simulation_id_exits_loan_exit_post

        Calculate Loan Exit
        """
        pass

    def test_get_exit_statistics_api_v1_simulations_simulation_id_exits_statistics_get(self) -> None:
        """Test case for get_exit_statistics_api_v1_simulations_simulation_id_exits_statistics_get

        Get Exit Statistics
        """
        pass

    def test_get_exit_visualization_api_v1_simulations_simulation_id_exits_visualization_get(self) -> None:
        """Test case for get_exit_visualization_api_v1_simulations_simulation_id_exits_visualization_get

        Get Exit Visualization
        """
        pass

    def test_get_exits_api_v1_simulations_simulation_id_exits_get(self) -> None:
        """Test case for get_exits_api_v1_simulations_simulation_id_exits_get

        Get Exits
        """
        pass

    def test_run_exit_scenario_api_v1_simulations_simulation_id_exits_scenario_post(self) -> None:
        """Test case for run_exit_scenario_api_v1_simulations_simulation_id_exits_scenario_post

        Run Exit Scenario
        """
        pass


if __name__ == '__main__':
    unittest.main()
