# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equihome_sim_sdk.models.liquidity_analysis import LiquidityAnalysis

class TestLiquidityAnalysis(unittest.TestCase):
    """LiquidityAnalysis unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LiquidityAnalysis:
        """Test LiquidityAnalysis
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LiquidityAnalysis`
        """
        model = LiquidityAnalysis()
        if include_optional:
            return LiquidityAnalysis(
                cash_reserves = [
                    equihome_sim_sdk.models.cash_reserve.CashReserve(
                        year = 56, 
                        month = 56, 
                        cash_reserve = 1.337, 
                        minimum_required = 1.337, 
                        shortfall = 1.337, )
                    ],
                liquidity_metrics = equihome_sim_sdk.models.liquidity_metrics.LiquidityMetrics(
                    min_cash_reserve = 1.337, 
                    max_cash_reserve = 1.337, 
                    avg_cash_reserve = 1.337, 
                    num_shortfall_periods = 56, 
                    max_shortfall = 1.337, )
            )
        else:
            return LiquidityAnalysis(
                cash_reserves = [
                    equihome_sim_sdk.models.cash_reserve.CashReserve(
                        year = 56, 
                        month = 56, 
                        cash_reserve = 1.337, 
                        minimum_required = 1.337, 
                        shortfall = 1.337, )
                    ],
                liquidity_metrics = equihome_sim_sdk.models.liquidity_metrics.LiquidityMetrics(
                    min_cash_reserve = 1.337, 
                    max_cash_reserve = 1.337, 
                    avg_cash_reserve = 1.337, 
                    num_shortfall_periods = 56, 
                    max_shortfall = 1.337, ),
        )
        """

    def testLiquidityAnalysis(self):
        """Test LiquidityAnalysis"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
