# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equihome_sim_sdk.models.risk_metrics_request import RiskMetricsRequest

class TestRiskMetricsRequest(unittest.TestCase):
    """RiskMetricsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RiskMetricsRequest:
        """Test RiskMetricsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RiskMetricsRequest`
        """
        model = RiskMetricsRequest()
        if include_optional:
            return RiskMetricsRequest(
                simulation_id = '',
                var_confidence_level = 1.337,
                risk_free_rate = 1.337,
                benchmark_return = 1.337,
                min_acceptable_return = 1.337,
                tail_risk_threshold = 1.337,
                monte_carlo_simulations = 56,
                enable_sensitivity_analysis = True,
                sensitivity_parameters = [
                    ''
                    ]
            )
        else:
            return RiskMetricsRequest(
                simulation_id = '',
        )
        """

    def testRiskMetricsRequest(self):
        """Test RiskMetricsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
