# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equihome_sim_sdk.api.enhanced_exit_simulator_api import EnhancedExitSimulatorApi


class TestEnhancedExitSimulatorApi(unittest.TestCase):
    """EnhancedExitSimulatorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EnhancedExitSimulatorApi()

    def tearDown(self) -> None:
        pass

    def test_get_enhanced_exit_statistics_api_v1_simulations_simulation_id_enhanced_exits_statistics_get(self) -> None:
        """Test case for get_enhanced_exit_statistics_api_v1_simulations_simulation_id_enhanced_exits_statistics_get

        Get Enhanced Exit Statistics
        """
        pass

    def test_get_enhanced_exit_visualization_api_v1_simulations_simulation_id_enhanced_exits_visualization_get(self) -> None:
        """Test case for get_enhanced_exit_visualization_api_v1_simulations_simulation_id_enhanced_exits_visualization_get

        Get Enhanced Exit Visualization
        """
        pass

    def test_get_enhanced_exits_api_v1_simulations_simulation_id_enhanced_exits_get(self) -> None:
        """Test case for get_enhanced_exits_api_v1_simulations_simulation_id_enhanced_exits_get

        Get Enhanced Exits
        """
        pass

    def test_run_enhanced_exit_scenario_api_v1_simulations_simulation_id_enhanced_exits_scenario_post(self) -> None:
        """Test case for run_enhanced_exit_scenario_api_v1_simulations_simulation_id_enhanced_exits_scenario_post

        Run Enhanced Exit Scenario
        """
        pass


if __name__ == '__main__':
    unittest.main()
