# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equihome_sim_sdk.models.performance_report_request import PerformanceReportRequest

class TestPerformanceReportRequest(unittest.TestCase):
    """PerformanceReportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PerformanceReportRequest:
        """Test PerformanceReportRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PerformanceReportRequest`
        """
        model = PerformanceReportRequest()
        if include_optional:
            return PerformanceReportRequest(
                simulation_id = '',
                include_kpi_table = True,
                include_zone_allocation = True,
                include_cash_flow = True,
                include_risk_metrics = True,
                include_tranche_performance = True,
                include_loan_performance = True,
                include_visualization = True,
                export_format = 'json',
                export_path = 'reports'
            )
        else:
            return PerformanceReportRequest(
                simulation_id = '',
        )
        """

    def testPerformanceReportRequest(self):
        """Test PerformanceReportRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
