# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equihome_sim_sdk.models.fund_level_metrics import FundLevelMetrics

class TestFundLevelMetrics(unittest.TestCase):
    """FundLevelMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FundLevelMetrics:
        """Test FundLevelMetrics
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FundLevelMetrics`
        """
        model = FundLevelMetrics()
        if include_optional:
            return FundLevelMetrics(
                irr = 1.337,
                moic = 1.337,
                tvpi = 1.337,
                dpi = 1.337,
                rvpi = 1.337,
                payback_period = 1.337,
                cash_on_cash = 1.337,
                npv = 1.337,
                profitability_index = 1.337,
                cash_yield = 1.337
            )
        else:
            return FundLevelMetrics(
                irr = 1.337,
                moic = 1.337,
                tvpi = 1.337,
                dpi = 1.337,
                rvpi = 1.337,
                payback_period = 1.337,
                cash_on_cash = 1.337,
                npv = 1.337,
                profitability_index = 1.337,
                cash_yield = 1.337,
        )
        """

    def testFundLevelMetrics(self):
        """Test FundLevelMetrics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
