# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equihome_sim_sdk.api.reinvestment_api import ReinvestmentApi


class TestReinvestmentApi(unittest.TestCase):
    """ReinvestmentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReinvestmentApi()

    def tearDown(self) -> None:
        pass

    def test_get_reinvestment_data_api_v1_simulations_simulation_id_reinvestment_get(self) -> None:
        """Test case for get_reinvestment_data_api_v1_simulations_simulation_id_reinvestment_get

        Get Reinvestment Data
        """
        pass

    def test_get_reinvestment_risk_metrics_api_v1_simulations_simulation_id_reinvestment_risk_get(self) -> None:
        """Test case for get_reinvestment_risk_metrics_api_v1_simulations_simulation_id_reinvestment_risk_get

        Get Reinvestment Risk Metrics
        """
        pass

    def test_manual_reinvestment_api_v1_simulations_simulation_id_reinvestment_post(self) -> None:
        """Test case for manual_reinvestment_api_v1_simulations_simulation_id_reinvestment_post

        Manual Reinvestment
        """
        pass


if __name__ == '__main__':
    unittest.main()
