# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equihome_sim_sdk.api.guardrail_api import GuardrailApi


class TestGuardrailApi(unittest.TestCase):
    """GuardrailApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GuardrailApi()

    def tearDown(self) -> None:
        pass

    def test_evaluate_guardrails_guardrail_evaluate_post(self) -> None:
        """Test case for evaluate_guardrails_guardrail_evaluate_post

        Evaluate Guardrails
        """
        pass

    def test_get_guardrail_report_guardrail_simulation_id_get(self) -> None:
        """Test case for get_guardrail_report_guardrail_simulation_id_get

        Get Guardrail Report
        """
        pass


if __name__ == '__main__':
    unittest.main()
