# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equihome_sim_sdk.models.sensitivity_analysis import SensitivityAnalysis

class TestSensitivityAnalysis(unittest.TestCase):
    """SensitivityAnalysis unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SensitivityAnalysis:
        """Test SensitivityAnalysis
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SensitivityAnalysis`
        """
        model = SensitivityAnalysis()
        if include_optional:
            return SensitivityAnalysis(
                parameter_variations = [
                    equihome_sim_sdk.models.parameter_variation.ParameterVariation(
                        parameter = '', 
                        value = 1.337, 
                        metrics = {
                            'key' : 1.337
                            }, )
                    ],
                tornado_chart = [
                    equihome_sim_sdk.models.tornado_chart_item.TornadoChartItem(
                        parameter = '', 
                        low_value = 1.337, 
                        high_value = 1.337, 
                        low_metric = 1.337, 
                        high_metric = 1.337, 
                        base_metric = 1.337, 
                        metric_name = '', )
                    ]
            )
        else:
            return SensitivityAnalysis(
                parameter_variations = [
                    equihome_sim_sdk.models.parameter_variation.ParameterVariation(
                        parameter = '', 
                        value = 1.337, 
                        metrics = {
                            'key' : 1.337
                            }, )
                    ],
                tornado_chart = [
                    equihome_sim_sdk.models.tornado_chart_item.TornadoChartItem(
                        parameter = '', 
                        low_value = 1.337, 
                        high_value = 1.337, 
                        low_metric = 1.337, 
                        high_metric = 1.337, 
                        base_metric = 1.337, 
                        metric_name = '', )
                    ],
        )
        """

    def testSensitivityAnalysis(self):
        """Test SensitivityAnalysis"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
