# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equihome_sim_sdk.api.portfolio_api import PortfolioApi


class TestPortfolioApi(unittest.TestCase):
    """PortfolioApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PortfolioApi()

    def tearDown(self) -> None:
        pass

    def test_get_allocation_history_simulations_simulation_id_allocation_history_get(self) -> None:
        """Test case for get_allocation_history_simulations_simulation_id_allocation_history_get

        Get Allocation History
        """
        pass

    def test_get_capital_allocation_simulations_simulation_id_capital_allocation_get(self) -> None:
        """Test case for get_capital_allocation_simulations_simulation_id_capital_allocation_get

        Get Capital Allocation
        """
        pass

    def test_get_leverage_events_simulations_simulation_id_leverage_events_get(self) -> None:
        """Test case for get_leverage_events_simulations_simulation_id_leverage_events_get

        Get Leverage Events
        """
        pass

    def test_get_leverage_facilities_simulations_simulation_id_leverage_facilities_get(self) -> None:
        """Test case for get_leverage_facilities_simulations_simulation_id_leverage_facilities_get

        Get Leverage Facilities
        """
        pass

    def test_get_leverage_metrics_simulations_simulation_id_leverage_metrics_get(self) -> None:
        """Test case for get_leverage_metrics_simulations_simulation_id_leverage_metrics_get

        Get Leverage Metrics
        """
        pass

    def test_get_leverage_simulations_simulation_id_leverage_get(self) -> None:
        """Test case for get_leverage_simulations_simulation_id_leverage_get

        Get Leverage
        """
        pass

    def test_get_loan_portfolio_history_simulations_simulation_id_loan_portfolio_history_get(self) -> None:
        """Test case for get_loan_portfolio_history_simulations_simulation_id_loan_portfolio_history_get

        Get Loan Portfolio History
        """
        pass

    def test_get_loan_portfolio_simulations_simulation_id_loan_portfolio_get(self) -> None:
        """Test case for get_loan_portfolio_simulations_simulation_id_loan_portfolio_get

        Get Loan Portfolio
        """
        pass

    def test_get_loans_simulations_simulation_id_loans_get(self) -> None:
        """Test case for get_loans_simulations_simulation_id_loans_get

        Get Loans
        """
        pass

    def test_get_rebalancing_recommendation_simulations_simulation_id_rebalancing_recommendation_get(self) -> None:
        """Test case for get_rebalancing_recommendation_simulations_simulation_id_rebalancing_recommendation_get

        Get Rebalancing Recommendation
        """
        pass

    def test_get_visualizations_simulations_simulation_id_visualizations_get(self) -> None:
        """Test case for get_visualizations_simulations_simulation_id_visualizations_get

        Get Visualizations
        """
        pass

    def test_reinvest_simulations_simulation_id_reinvest_post(self) -> None:
        """Test case for reinvest_simulations_simulation_id_reinvest_post

        Reinvest
        """
        pass


if __name__ == '__main__':
    unittest.main()
