# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equihome_sim_sdk.api.tls_api import TlsApi


class TestTlsApi(unittest.TestCase):
    """TlsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TlsApi()

    def tearDown(self) -> None:
        pass

    def test_get_metric_correlations_tls_correlations_metrics_get(self) -> None:
        """Test case for get_metric_correlations_tls_correlations_metrics_get

        Get Metric Correlations
        """
        pass

    def test_get_metric_distribution_tls_metrics_metric_name_distribution_get(self) -> None:
        """Test case for get_metric_distribution_tls_metrics_metric_name_distribution_get

        Get Metric Distribution
        """
        pass

    def test_get_metrics_tls_metrics_get(self) -> None:
        """Test case for get_metrics_tls_metrics_get

        Get Metrics
        """
        pass

    def test_get_property_distribution_tls_visualization_property_distribution_get(self) -> None:
        """Test case for get_property_distribution_tls_visualization_property_distribution_get

        Get Property Distribution
        """
        pass

    def test_get_suburb_tls_suburbs_suburb_id_get(self) -> None:
        """Test case for get_suburb_tls_suburbs_suburb_id_get

        Get Suburb
        """
        pass

    def test_get_suburbs_tls_suburbs_get(self) -> None:
        """Test case for get_suburbs_tls_suburbs_get

        Get Suburbs
        """
        pass

    def test_get_zone_distribution_tls_zones_distribution_get(self) -> None:
        """Test case for get_zone_distribution_tls_zones_distribution_get

        Get Zone Distribution
        """
        pass

    def test_get_zone_map_tls_visualization_zone_map_get(self) -> None:
        """Test case for get_zone_map_tls_visualization_zone_map_get

        Get Zone Map
        """
        pass


if __name__ == '__main__':
    unittest.main()
