# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equihome_sim_sdk.models.src_api_routers_reinvestment_reinvestment_response import SrcApiRoutersReinvestmentReinvestmentResponse

class TestSrcApiRoutersReinvestmentReinvestmentResponse(unittest.TestCase):
    """SrcApiRoutersReinvestmentReinvestmentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SrcApiRoutersReinvestmentReinvestmentResponse:
        """Test SrcApiRoutersReinvestmentReinvestmentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SrcApiRoutersReinvestmentReinvestmentResponse`
        """
        model = SrcApiRoutersReinvestmentReinvestmentResponse()
        if include_optional:
            return SrcApiRoutersReinvestmentReinvestmentResponse(
                events = [
                    equihome_sim_sdk.models.reinvestment_event_response.ReinvestmentEventResponse(
                        event_id = '', 
                        timestamp = 1.337, 
                        year = 1.337, 
                        month = 56, 
                        amount = 1.337, 
                        source = '', 
                        source_details = equihome_sim_sdk.models.source_details.Source Details(), 
                        strategy_used = '', 
                        target_allocations = {
                            'key' : 1.337
                            }, 
                        actual_allocations = {
                            'key' : 1.337
                            }, 
                        num_loans_generated = 56, 
                        loan_ids = [
                            ''
                            ], 
                        performance_adjustments = {
                            'key' : 1.337
                            }, 
                        cash_reserve_before = 1.337, 
                        cash_reserve_after = 1.337, )
                    ],
                summary = equihome_sim_sdk.models.reinvestment_summary_response.ReinvestmentSummaryResponse(
                    total_reinvested = 1.337, 
                    num_reinvestment_events = 56, 
                    avg_reinvestment_amount = 1.337, 
                    reinvestment_by_year = {
                        'key' : 1.337
                        }, 
                    reinvestment_by_zone = {
                        'key' : 1.337
                        }, 
                    reinvestment_by_strategy = {
                        'key' : 1.337
                        }, 
                    reinvestment_by_source = {
                        'key' : 1.337
                        }, 
                    reinvestment_efficiency = null, 
                    reinvestment_performance = null, 
                    reinvestment_timing = {
                        'key' : {
                            'key' : 1.337
                            }
                        }, 
                    cash_reserve_history = [
                        None
                        ], 
                    cash_reserve_metrics = null, ),
                visualization = equihome_sim_sdk.models.reinvestment_visualization_response.ReinvestmentVisualizationResponse(
                    charts = null, 
                    tables = null, 
                    kpis = null, )
            )
        else:
            return SrcApiRoutersReinvestmentReinvestmentResponse(
                events = [
                    equihome_sim_sdk.models.reinvestment_event_response.ReinvestmentEventResponse(
                        event_id = '', 
                        timestamp = 1.337, 
                        year = 1.337, 
                        month = 56, 
                        amount = 1.337, 
                        source = '', 
                        source_details = equihome_sim_sdk.models.source_details.Source Details(), 
                        strategy_used = '', 
                        target_allocations = {
                            'key' : 1.337
                            }, 
                        actual_allocations = {
                            'key' : 1.337
                            }, 
                        num_loans_generated = 56, 
                        loan_ids = [
                            ''
                            ], 
                        performance_adjustments = {
                            'key' : 1.337
                            }, 
                        cash_reserve_before = 1.337, 
                        cash_reserve_after = 1.337, )
                    ],
                summary = equihome_sim_sdk.models.reinvestment_summary_response.ReinvestmentSummaryResponse(
                    total_reinvested = 1.337, 
                    num_reinvestment_events = 56, 
                    avg_reinvestment_amount = 1.337, 
                    reinvestment_by_year = {
                        'key' : 1.337
                        }, 
                    reinvestment_by_zone = {
                        'key' : 1.337
                        }, 
                    reinvestment_by_strategy = {
                        'key' : 1.337
                        }, 
                    reinvestment_by_source = {
                        'key' : 1.337
                        }, 
                    reinvestment_efficiency = null, 
                    reinvestment_performance = null, 
                    reinvestment_timing = {
                        'key' : {
                            'key' : 1.337
                            }
                        }, 
                    cash_reserve_history = [
                        None
                        ], 
                    cash_reserve_metrics = null, ),
                visualization = equihome_sim_sdk.models.reinvestment_visualization_response.ReinvestmentVisualizationResponse(
                    charts = null, 
                    tables = null, 
                    kpis = null, ),
        )
        """

    def testSrcApiRoutersReinvestmentReinvestmentResponse(self):
        """Test SrcApiRoutersReinvestmentReinvestmentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
