# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equihome_sim_sdk.models.credit_metrics import CreditMetrics

class TestCreditMetrics(unittest.TestCase):
    """CreditMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreditMetrics:
        """Test CreditMetrics
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreditMetrics`
        """
        model = CreditMetrics()
        if include_optional:
            return CreditMetrics(
                current_ltv = equihome_sim_sdk.models.current_ltv.Current Ltv(),
                stress_ltv = equihome_sim_sdk.models.stress_ltv.Stress Ltv(),
                default_probability = equihome_sim_sdk.models.default_probability.Default Probability(),
                portfolio_default_rate = 1.337
            )
        else:
            return CreditMetrics(
                current_ltv = equihome_sim_sdk.models.current_ltv.Current Ltv(),
                stress_ltv = equihome_sim_sdk.models.stress_ltv.Stress Ltv(),
                default_probability = equihome_sim_sdk.models.default_probability.Default Probability(),
                portfolio_default_rate = 1.337,
        )
        """

    def testCreditMetrics(self):
        """Test CreditMetrics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
