/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Cash reserve metrics response model.
 * @export
 * @interface CashReserveMetricsResponse
 */
export interface CashReserveMetricsResponse {
    /**
     * Average cash reserve
     * @type {number}
     * @memberof CashReserveMetricsResponse
     */
    avgCashReserve: number;
    /**
     * Minimum cash reserve
     * @type {number}
     * @memberof CashReserveMetricsResponse
     */
    minCashReserve: number;
    /**
     * Maximum cash reserve
     * @type {number}
     * @memberof CashReserveMetricsResponse
     */
    maxCashReserve: number;
    /**
     * Average cash reserve as percentage of fund size
     * @type {number}
     * @memberof CashReserveMetricsResponse
     */
    avgCashReservePct: number;
    /**
     * Minimum cash reserve as percentage of fund size
     * @type {number}
     * @memberof CashReserveMetricsResponse
     */
    minCashReservePct: number;
    /**
     * Maximum cash reserve as percentage of fund size
     * @type {number}
     * @memberof CashReserveMetricsResponse
     */
    maxCashReservePct: number;
}

/**
 * Check if a given object implements the CashReserveMetricsResponse interface.
 */
export function instanceOfCashReserveMetricsResponse(value: object): value is CashReserveMetricsResponse {
    if (!('avgCashReserve' in value) || value['avgCashReserve'] === undefined) return false;
    if (!('minCashReserve' in value) || value['minCashReserve'] === undefined) return false;
    if (!('maxCashReserve' in value) || value['maxCashReserve'] === undefined) return false;
    if (!('avgCashReservePct' in value) || value['avgCashReservePct'] === undefined) return false;
    if (!('minCashReservePct' in value) || value['minCashReservePct'] === undefined) return false;
    if (!('maxCashReservePct' in value) || value['maxCashReservePct'] === undefined) return false;
    return true;
}

export function CashReserveMetricsResponseFromJSON(json: any): CashReserveMetricsResponse {
    return CashReserveMetricsResponseFromJSONTyped(json, false);
}

export function CashReserveMetricsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashReserveMetricsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'avgCashReserve': json['avg_cash_reserve'],
        'minCashReserve': json['min_cash_reserve'],
        'maxCashReserve': json['max_cash_reserve'],
        'avgCashReservePct': json['avg_cash_reserve_pct'],
        'minCashReservePct': json['min_cash_reserve_pct'],
        'maxCashReservePct': json['max_cash_reserve_pct'],
    };
}

export function CashReserveMetricsResponseToJSON(json: any): CashReserveMetricsResponse {
    return CashReserveMetricsResponseToJSONTyped(json, false);
}

export function CashReserveMetricsResponseToJSONTyped(value?: CashReserveMetricsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avg_cash_reserve': value['avgCashReserve'],
        'min_cash_reserve': value['minCashReserve'],
        'max_cash_reserve': value['maxCashReserve'],
        'avg_cash_reserve_pct': value['avgCashReservePct'],
        'min_cash_reserve_pct': value['minCashReservePct'],
        'max_cash_reserve_pct': value['maxCashReservePct'],
    };
}

