/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for fee calculation.
 * @export
 * @interface FeeCalculationRequest
 */
export interface FeeCalculationRequest {
    /**
     * Simulation ID
     * @type {string}
     * @memberof FeeCalculationRequest
     */
    simulationId: string;
    /**
     * Management fee rate (0-1)
     * @type {number}
     * @memberof FeeCalculationRequest
     */
    managementFeeRate?: number;
    /**
     * Basis for management fee calculation
     * @type {string}
     * @memberof FeeCalculationRequest
     */
    managementFeeBasis?: FeeCalculationRequestManagementFeeBasisEnum;
    /**
     * Origination fee rate (0-1)
     * @type {number}
     * @memberof FeeCalculationRequest
     */
    originationFeeRate?: number;
    /**
     * Annual fund expenses as percentage of fund size (0-1)
     * @type {number}
     * @memberof FeeCalculationRequest
     */
    annualFundExpenses?: number;
    /**
     * Fixed annual expenses in dollars
     * @type {number}
     * @memberof FeeCalculationRequest
     */
    fixedAnnualExpenses?: number;
    /**
     * Annual growth rate for expenses (0-1)
     * @type {number}
     * @memberof FeeCalculationRequest
     */
    expenseGrowthRate?: number;
    /**
     * Acquisition fee rate (0-1)
     * @type {number}
     * @memberof FeeCalculationRequest
     */
    acquisitionFeeRate?: number;
    /**
     * Disposition fee rate (0-1)
     * @type {number}
     * @memberof FeeCalculationRequest
     */
    dispositionFeeRate?: number;
    /**
     * One-time setup costs in dollars
     * @type {number}
     * @memberof FeeCalculationRequest
     */
    setupCosts?: number;
}


/**
 * @export
 */
export const FeeCalculationRequestManagementFeeBasisEnum = {
    CommittedCapital: 'committed_capital',
    InvestedCapital: 'invested_capital',
    NetAssetValue: 'net_asset_value'
} as const;
export type FeeCalculationRequestManagementFeeBasisEnum = typeof FeeCalculationRequestManagementFeeBasisEnum[keyof typeof FeeCalculationRequestManagementFeeBasisEnum];


/**
 * Check if a given object implements the FeeCalculationRequest interface.
 */
export function instanceOfFeeCalculationRequest(value: object): value is FeeCalculationRequest {
    if (!('simulationId' in value) || value['simulationId'] === undefined) return false;
    return true;
}

export function FeeCalculationRequestFromJSON(json: any): FeeCalculationRequest {
    return FeeCalculationRequestFromJSONTyped(json, false);
}

export function FeeCalculationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeeCalculationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'simulationId': json['simulation_id'],
        'managementFeeRate': json['management_fee_rate'] == null ? undefined : json['management_fee_rate'],
        'managementFeeBasis': json['management_fee_basis'] == null ? undefined : json['management_fee_basis'],
        'originationFeeRate': json['origination_fee_rate'] == null ? undefined : json['origination_fee_rate'],
        'annualFundExpenses': json['annual_fund_expenses'] == null ? undefined : json['annual_fund_expenses'],
        'fixedAnnualExpenses': json['fixed_annual_expenses'] == null ? undefined : json['fixed_annual_expenses'],
        'expenseGrowthRate': json['expense_growth_rate'] == null ? undefined : json['expense_growth_rate'],
        'acquisitionFeeRate': json['acquisition_fee_rate'] == null ? undefined : json['acquisition_fee_rate'],
        'dispositionFeeRate': json['disposition_fee_rate'] == null ? undefined : json['disposition_fee_rate'],
        'setupCosts': json['setup_costs'] == null ? undefined : json['setup_costs'],
    };
}

export function FeeCalculationRequestToJSON(json: any): FeeCalculationRequest {
    return FeeCalculationRequestToJSONTyped(json, false);
}

export function FeeCalculationRequestToJSONTyped(value?: FeeCalculationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'simulation_id': value['simulationId'],
        'management_fee_rate': value['managementFeeRate'],
        'management_fee_basis': value['managementFeeBasis'],
        'origination_fee_rate': value['originationFeeRate'],
        'annual_fund_expenses': value['annualFundExpenses'],
        'fixed_annual_expenses': value['fixedAnnualExpenses'],
        'expense_growth_rate': value['expenseGrowthRate'],
        'acquisition_fee_rate': value['acquisitionFeeRate'],
        'disposition_fee_rate': value['dispositionFeeRate'],
        'setup_costs': value['setupCosts'],
    };
}

