/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeeImpactItem } from './FeeImpactItem';
import {
    FeeImpactItemFromJSON,
    FeeImpactItemFromJSONTyped,
    FeeImpactItemToJSON,
    FeeImpactItemToJSONTyped,
} from './FeeImpactItem';
import type { FeeBreakdownItem } from './FeeBreakdownItem';
import {
    FeeBreakdownItemFromJSON,
    FeeBreakdownItemFromJSONTyped,
    FeeBreakdownItemToJSON,
    FeeBreakdownItemToJSONTyped,
} from './FeeBreakdownItem';
import type { FeesByYearItem } from './FeesByYearItem';
import {
    FeesByYearItemFromJSON,
    FeesByYearItemFromJSONTyped,
    FeesByYearItemToJSON,
    FeesByYearItemToJSONTyped,
} from './FeesByYearItem';

/**
 * Fee visualization model.
 * @export
 * @interface FeeVisualization
 */
export interface FeeVisualization {
    /**
     * Fee breakdown chart data
     * @type {Array<FeeBreakdownItem>}
     * @memberof FeeVisualization
     */
    feeBreakdownChart: Array<FeeBreakdownItem>;
    /**
     * Fees by year chart data
     * @type {Array<FeesByYearItem>}
     * @memberof FeeVisualization
     */
    feesByYearChart: Array<FeesByYearItem>;
    /**
     * Fee impact chart data
     * @type {Array<FeeImpactItem>}
     * @memberof FeeVisualization
     */
    feeImpactChart: Array<FeeImpactItem>;
    /**
     * Fee table data
     * @type {Array<FeesByYearItem>}
     * @memberof FeeVisualization
     */
    feeTable: Array<FeesByYearItem>;
}

/**
 * Check if a given object implements the FeeVisualization interface.
 */
export function instanceOfFeeVisualization(value: object): value is FeeVisualization {
    if (!('feeBreakdownChart' in value) || value['feeBreakdownChart'] === undefined) return false;
    if (!('feesByYearChart' in value) || value['feesByYearChart'] === undefined) return false;
    if (!('feeImpactChart' in value) || value['feeImpactChart'] === undefined) return false;
    if (!('feeTable' in value) || value['feeTable'] === undefined) return false;
    return true;
}

export function FeeVisualizationFromJSON(json: any): FeeVisualization {
    return FeeVisualizationFromJSONTyped(json, false);
}

export function FeeVisualizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeeVisualization {
    if (json == null) {
        return json;
    }
    return {
        
        'feeBreakdownChart': ((json['fee_breakdown_chart'] as Array<any>).map(FeeBreakdownItemFromJSON)),
        'feesByYearChart': ((json['fees_by_year_chart'] as Array<any>).map(FeesByYearItemFromJSON)),
        'feeImpactChart': ((json['fee_impact_chart'] as Array<any>).map(FeeImpactItemFromJSON)),
        'feeTable': ((json['fee_table'] as Array<any>).map(FeesByYearItemFromJSON)),
    };
}

export function FeeVisualizationToJSON(json: any): FeeVisualization {
    return FeeVisualizationToJSONTyped(json, false);
}

export function FeeVisualizationToJSONTyped(value?: FeeVisualization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fee_breakdown_chart': ((value['feeBreakdownChart'] as Array<any>).map(FeeBreakdownItemToJSON)),
        'fees_by_year_chart': ((value['feesByYearChart'] as Array<any>).map(FeesByYearItemToJSON)),
        'fee_impact_chart': ((value['feeImpactChart'] as Array<any>).map(FeeImpactItemToJSON)),
        'fee_table': ((value['feeTable'] as Array<any>).map(FeesByYearItemToJSON)),
    };
}

