/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Loan-level cashflow model.
 * @export
 * @interface LoanLevelCashflow
 */
export interface LoanLevelCashflow {
    /**
     * Loan ID
     * @type {string}
     * @memberof LoanLevelCashflow
     */
    loanId: string;
    /**
     * Origination cashflows
     * @type {object}
     * @memberof LoanLevelCashflow
     */
    origination: object;
    /**
     * Exit cashflows
     * @type {object}
     * @memberof LoanLevelCashflow
     */
    exit?: object;
}

/**
 * Check if a given object implements the LoanLevelCashflow interface.
 */
export function instanceOfLoanLevelCashflow(value: object): value is LoanLevelCashflow {
    if (!('loanId' in value) || value['loanId'] === undefined) return false;
    if (!('origination' in value) || value['origination'] === undefined) return false;
    return true;
}

export function LoanLevelCashflowFromJSON(json: any): LoanLevelCashflow {
    return LoanLevelCashflowFromJSONTyped(json, false);
}

export function LoanLevelCashflowFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoanLevelCashflow {
    if (json == null) {
        return json;
    }
    return {
        
        'loanId': json['loan_id'],
        'origination': json['origination'],
        'exit': json['exit'] == null ? undefined : json['exit'],
    };
}

export function LoanLevelCashflowToJSON(json: any): LoanLevelCashflow {
    return LoanLevelCashflowToJSONTyped(json, false);
}

export function LoanLevelCashflowToJSONTyped(value?: LoanLevelCashflow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'loan_id': value['loanId'],
        'origination': value['origination'],
        'exit': value['exit'],
    };
}

