/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * LP metrics model.
 * @export
 * @interface LPMetrics
 */
export interface LPMetrics {
    /**
     * Internal Rate of Return
     * @type {number}
     * @memberof LPMetrics
     */
    irr: number;
    /**
     * Multiple on Invested Capital
     * @type {number}
     * @memberof LPMetrics
     */
    moic: number;
    /**
     * Total Value to Paid-In
     * @type {number}
     * @memberof LPMetrics
     */
    tvpi: number;
    /**
     * Distributions to Paid-In
     * @type {number}
     * @memberof LPMetrics
     */
    dpi: number;
    /**
     * Residual Value to Paid-In
     * @type {number}
     * @memberof LPMetrics
     */
    rvpi: number;
    /**
     * Payback period in years
     * @type {number}
     * @memberof LPMetrics
     */
    paybackPeriod: number;
}

/**
 * Check if a given object implements the LPMetrics interface.
 */
export function instanceOfLPMetrics(value: object): value is LPMetrics {
    if (!('irr' in value) || value['irr'] === undefined) return false;
    if (!('moic' in value) || value['moic'] === undefined) return false;
    if (!('tvpi' in value) || value['tvpi'] === undefined) return false;
    if (!('dpi' in value) || value['dpi'] === undefined) return false;
    if (!('rvpi' in value) || value['rvpi'] === undefined) return false;
    if (!('paybackPeriod' in value) || value['paybackPeriod'] === undefined) return false;
    return true;
}

export function LPMetricsFromJSON(json: any): LPMetrics {
    return LPMetricsFromJSONTyped(json, false);
}

export function LPMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LPMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'irr': json['irr'],
        'moic': json['moic'],
        'tvpi': json['tvpi'],
        'dpi': json['dpi'],
        'rvpi': json['rvpi'],
        'paybackPeriod': json['payback_period'],
    };
}

export function LPMetricsToJSON(json: any): LPMetrics {
    return LPMetricsToJSONTyped(json, false);
}

export function LPMetricsToJSONTyped(value?: LPMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'irr': value['irr'],
        'moic': value['moic'],
        'tvpi': value['tvpi'],
        'dpi': value['dpi'],
        'rvpi': value['rvpi'],
        'payback_period': value['paybackPeriod'],
    };
}

