/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReinvestmentEfficiencyResponse } from './ReinvestmentEfficiencyResponse';
import {
    ReinvestmentEfficiencyResponseFromJSON,
    ReinvestmentEfficiencyResponseFromJSONTyped,
    ReinvestmentEfficiencyResponseToJSON,
    ReinvestmentEfficiencyResponseToJSONTyped,
} from './ReinvestmentEfficiencyResponse';
import type { CashReserveMetricsResponse } from './CashReserveMetricsResponse';
import {
    CashReserveMetricsResponseFromJSON,
    CashReserveMetricsResponseFromJSONTyped,
    CashReserveMetricsResponseToJSON,
    CashReserveMetricsResponseToJSONTyped,
} from './CashReserveMetricsResponse';
import type { ReinvestmentPerformanceResponse } from './ReinvestmentPerformanceResponse';
import {
    ReinvestmentPerformanceResponseFromJSON,
    ReinvestmentPerformanceResponseFromJSONTyped,
    ReinvestmentPerformanceResponseToJSON,
    ReinvestmentPerformanceResponseToJSONTyped,
} from './ReinvestmentPerformanceResponse';

/**
 * Reinvestment summary response model.
 * @export
 * @interface ReinvestmentSummaryResponse
 */
export interface ReinvestmentSummaryResponse {
    /**
     * Total amount reinvested
     * @type {number}
     * @memberof ReinvestmentSummaryResponse
     */
    totalReinvested: number;
    /**
     * Number of reinvestment events
     * @type {number}
     * @memberof ReinvestmentSummaryResponse
     */
    numReinvestmentEvents: number;
    /**
     * Average reinvestment amount
     * @type {number}
     * @memberof ReinvestmentSummaryResponse
     */
    avgReinvestmentAmount: number;
    /**
     * Reinvestment amounts by year
     * @type {{ [key: string]: number; }}
     * @memberof ReinvestmentSummaryResponse
     */
    reinvestmentByYear: { [key: string]: number; };
    /**
     * Reinvestment amounts by zone
     * @type {{ [key: string]: number; }}
     * @memberof ReinvestmentSummaryResponse
     */
    reinvestmentByZone: { [key: string]: number; };
    /**
     * Reinvestment amounts by strategy
     * @type {{ [key: string]: number; }}
     * @memberof ReinvestmentSummaryResponse
     */
    reinvestmentByStrategy: { [key: string]: number; };
    /**
     * Reinvestment amounts by source
     * @type {{ [key: string]: number; }}
     * @memberof ReinvestmentSummaryResponse
     */
    reinvestmentBySource: { [key: string]: number; };
    /**
     * Reinvestment efficiency metrics
     * @type {ReinvestmentEfficiencyResponse}
     * @memberof ReinvestmentSummaryResponse
     */
    reinvestmentEfficiency?: ReinvestmentEfficiencyResponse;
    /**
     * Reinvestment performance metrics
     * @type {ReinvestmentPerformanceResponse}
     * @memberof ReinvestmentSummaryResponse
     */
    reinvestmentPerformance?: ReinvestmentPerformanceResponse;
    /**
     * Reinvestment timing by year and quarter
     * @type {{ [key: string]: { [key: string]: number; }; }}
     * @memberof ReinvestmentSummaryResponse
     */
    reinvestmentTiming?: { [key: string]: { [key: string]: number; }; };
    /**
     * Cash reserve history
     * @type {Array<object>}
     * @memberof ReinvestmentSummaryResponse
     */
    cashReserveHistory?: Array<object>;
    /**
     * Cash reserve metrics
     * @type {CashReserveMetricsResponse}
     * @memberof ReinvestmentSummaryResponse
     */
    cashReserveMetrics?: CashReserveMetricsResponse;
}

/**
 * Check if a given object implements the ReinvestmentSummaryResponse interface.
 */
export function instanceOfReinvestmentSummaryResponse(value: object): value is ReinvestmentSummaryResponse {
    if (!('totalReinvested' in value) || value['totalReinvested'] === undefined) return false;
    if (!('numReinvestmentEvents' in value) || value['numReinvestmentEvents'] === undefined) return false;
    if (!('avgReinvestmentAmount' in value) || value['avgReinvestmentAmount'] === undefined) return false;
    if (!('reinvestmentByYear' in value) || value['reinvestmentByYear'] === undefined) return false;
    if (!('reinvestmentByZone' in value) || value['reinvestmentByZone'] === undefined) return false;
    if (!('reinvestmentByStrategy' in value) || value['reinvestmentByStrategy'] === undefined) return false;
    if (!('reinvestmentBySource' in value) || value['reinvestmentBySource'] === undefined) return false;
    return true;
}

export function ReinvestmentSummaryResponseFromJSON(json: any): ReinvestmentSummaryResponse {
    return ReinvestmentSummaryResponseFromJSONTyped(json, false);
}

export function ReinvestmentSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReinvestmentSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalReinvested': json['total_reinvested'],
        'numReinvestmentEvents': json['num_reinvestment_events'],
        'avgReinvestmentAmount': json['avg_reinvestment_amount'],
        'reinvestmentByYear': json['reinvestment_by_year'],
        'reinvestmentByZone': json['reinvestment_by_zone'],
        'reinvestmentByStrategy': json['reinvestment_by_strategy'],
        'reinvestmentBySource': json['reinvestment_by_source'],
        'reinvestmentEfficiency': json['reinvestment_efficiency'] == null ? undefined : ReinvestmentEfficiencyResponseFromJSON(json['reinvestment_efficiency']),
        'reinvestmentPerformance': json['reinvestment_performance'] == null ? undefined : ReinvestmentPerformanceResponseFromJSON(json['reinvestment_performance']),
        'reinvestmentTiming': json['reinvestment_timing'] == null ? undefined : json['reinvestment_timing'],
        'cashReserveHistory': json['cash_reserve_history'] == null ? undefined : json['cash_reserve_history'],
        'cashReserveMetrics': json['cash_reserve_metrics'] == null ? undefined : CashReserveMetricsResponseFromJSON(json['cash_reserve_metrics']),
    };
}

export function ReinvestmentSummaryResponseToJSON(json: any): ReinvestmentSummaryResponse {
    return ReinvestmentSummaryResponseToJSONTyped(json, false);
}

export function ReinvestmentSummaryResponseToJSONTyped(value?: ReinvestmentSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_reinvested': value['totalReinvested'],
        'num_reinvestment_events': value['numReinvestmentEvents'],
        'avg_reinvestment_amount': value['avgReinvestmentAmount'],
        'reinvestment_by_year': value['reinvestmentByYear'],
        'reinvestment_by_zone': value['reinvestmentByZone'],
        'reinvestment_by_strategy': value['reinvestmentByStrategy'],
        'reinvestment_by_source': value['reinvestmentBySource'],
        'reinvestment_efficiency': ReinvestmentEfficiencyResponseToJSON(value['reinvestmentEfficiency']),
        'reinvestment_performance': ReinvestmentPerformanceResponseToJSON(value['reinvestmentPerformance']),
        'reinvestment_timing': value['reinvestmentTiming'],
        'cash_reserve_history': value['cashReserveHistory'],
        'cash_reserve_metrics': CashReserveMetricsResponseToJSON(value['cashReserveMetrics']),
    };
}

