/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SrcApiRoutersReinvestmentRiskMetricsResponse } from './SrcApiRoutersReinvestmentRiskMetricsResponse';
import {
    SrcApiRoutersReinvestmentRiskMetricsResponseFromJSON,
    SrcApiRoutersReinvestmentRiskMetricsResponseFromJSONTyped,
    SrcApiRoutersReinvestmentRiskMetricsResponseToJSON,
    SrcApiRoutersReinvestmentRiskMetricsResponseToJSONTyped,
} from './SrcApiRoutersReinvestmentRiskMetricsResponse';

/**
 * Reinvestment KPIs response model.
 * @export
 * @interface ReinvestmentKPIsResponse
 */
export interface ReinvestmentKPIsResponse {
    /**
     * Total amount reinvested
     * @type {number}
     * @memberof ReinvestmentKPIsResponse
     */
    totalReinvested: number;
    /**
     * Number of reinvestment events
     * @type {number}
     * @memberof ReinvestmentKPIsResponse
     */
    numReinvestmentEvents: number;
    /**
     * Average reinvestment amount
     * @type {number}
     * @memberof ReinvestmentKPIsResponse
     */
    avgReinvestmentAmount: number;
    /**
     * Ratio of reinvested capital to total exit value
     * @type {number}
     * @memberof ReinvestmentKPIsResponse
     */
    reinvestmentRatio: number;
    /**
     * Average time between exit and reinvestment in months
     * @type {number}
     * @memberof ReinvestmentKPIsResponse
     */
    avgTimeToReinvest: number;
    /**
     * Return on investment for reinvested capital
     * @type {number}
     * @memberof ReinvestmentKPIsResponse
     */
    reinvestmentRoi: number;
    /**
     * Number of reinvestment loans
     * @type {number}
     * @memberof ReinvestmentKPIsResponse
     */
    numReinvestmentLoans: number;
    /**
     * Percentage of portfolio from reinvestment
     * @type {number}
     * @memberof ReinvestmentKPIsResponse
     */
    reinvestmentPortfolioImpact: number;
    /**
     * Risk impact metrics
     * @type {SrcApiRoutersReinvestmentRiskMetricsResponse}
     * @memberof ReinvestmentKPIsResponse
     */
    riskMetrics?: SrcApiRoutersReinvestmentRiskMetricsResponse;
}

/**
 * Check if a given object implements the ReinvestmentKPIsResponse interface.
 */
export function instanceOfReinvestmentKPIsResponse(value: object): value is ReinvestmentKPIsResponse {
    if (!('totalReinvested' in value) || value['totalReinvested'] === undefined) return false;
    if (!('numReinvestmentEvents' in value) || value['numReinvestmentEvents'] === undefined) return false;
    if (!('avgReinvestmentAmount' in value) || value['avgReinvestmentAmount'] === undefined) return false;
    if (!('reinvestmentRatio' in value) || value['reinvestmentRatio'] === undefined) return false;
    if (!('avgTimeToReinvest' in value) || value['avgTimeToReinvest'] === undefined) return false;
    if (!('reinvestmentRoi' in value) || value['reinvestmentRoi'] === undefined) return false;
    if (!('numReinvestmentLoans' in value) || value['numReinvestmentLoans'] === undefined) return false;
    if (!('reinvestmentPortfolioImpact' in value) || value['reinvestmentPortfolioImpact'] === undefined) return false;
    return true;
}

export function ReinvestmentKPIsResponseFromJSON(json: any): ReinvestmentKPIsResponse {
    return ReinvestmentKPIsResponseFromJSONTyped(json, false);
}

export function ReinvestmentKPIsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReinvestmentKPIsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalReinvested': json['total_reinvested'],
        'numReinvestmentEvents': json['num_reinvestment_events'],
        'avgReinvestmentAmount': json['avg_reinvestment_amount'],
        'reinvestmentRatio': json['reinvestment_ratio'],
        'avgTimeToReinvest': json['avg_time_to_reinvest'],
        'reinvestmentRoi': json['reinvestment_roi'],
        'numReinvestmentLoans': json['num_reinvestment_loans'],
        'reinvestmentPortfolioImpact': json['reinvestment_portfolio_impact'],
        'riskMetrics': json['risk_metrics'] == null ? undefined : SrcApiRoutersReinvestmentRiskMetricsResponseFromJSON(json['risk_metrics']),
    };
}

export function ReinvestmentKPIsResponseToJSON(json: any): ReinvestmentKPIsResponse {
    return ReinvestmentKPIsResponseToJSONTyped(json, false);
}

export function ReinvestmentKPIsResponseToJSONTyped(value?: ReinvestmentKPIsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_reinvested': value['totalReinvested'],
        'num_reinvestment_events': value['numReinvestmentEvents'],
        'avg_reinvestment_amount': value['avgReinvestmentAmount'],
        'reinvestment_ratio': value['reinvestmentRatio'],
        'avg_time_to_reinvest': value['avgTimeToReinvest'],
        'reinvestment_roi': value['reinvestmentRoi'],
        'num_reinvestment_loans': value['numReinvestmentLoans'],
        'reinvestment_portfolio_impact': value['reinvestmentPortfolioImpact'],
        'risk_metrics': SrcApiRoutersReinvestmentRiskMetricsResponseToJSON(value['riskMetrics']),
    };
}

