/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Result response model.
 * @export
 * @interface ResultResponse
 */
export interface ResultResponse {
    /**
     * Simulation ID
     * @type {string}
     * @memberof ResultResponse
     */
    simulationId: string;
    /**
     * Simulation status
     * @type {string}
     * @memberof ResultResponse
     */
    status: string;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof ResultResponse
     */
    createdAt: string;
    /**
     * Completion timestamp
     * @type {string}
     * @memberof ResultResponse
     */
    completedAt?: string;
    /**
     * Simulation metrics
     * @type {object}
     * @memberof ResultResponse
     */
    metrics?: object;
    /**
     * Execution time in seconds
     * @type {number}
     * @memberof ResultResponse
     */
    executionTime?: number;
    /**
     * Number of loans
     * @type {number}
     * @memberof ResultResponse
     */
    numLoans?: number;
    /**
     * Guardrail violations
     * @type {Array<string>}
     * @memberof ResultResponse
     */
    guardrailViolations?: Array<string>;
}

/**
 * Check if a given object implements the ResultResponse interface.
 */
export function instanceOfResultResponse(value: object): value is ResultResponse {
    if (!('simulationId' in value) || value['simulationId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ResultResponseFromJSON(json: any): ResultResponse {
    return ResultResponseFromJSONTyped(json, false);
}

export function ResultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'simulationId': json['simulation_id'],
        'status': json['status'],
        'createdAt': json['created_at'],
        'completedAt': json['completed_at'] == null ? undefined : json['completed_at'],
        'metrics': json['metrics'] == null ? undefined : json['metrics'],
        'executionTime': json['execution_time'] == null ? undefined : json['execution_time'],
        'numLoans': json['num_loans'] == null ? undefined : json['num_loans'],
        'guardrailViolations': json['guardrail_violations'] == null ? undefined : json['guardrail_violations'],
    };
}

export function ResultResponseToJSON(json: any): ResultResponse {
    return ResultResponseToJSONTyped(json, false);
}

export function ResultResponseToJSONTyped(value?: ResultResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'simulation_id': value['simulationId'],
        'status': value['status'],
        'created_at': value['createdAt'],
        'completed_at': value['completedAt'],
        'metrics': value['metrics'],
        'execution_time': value['executionTime'],
        'num_loans': value['numLoans'],
        'guardrail_violations': value['guardrailViolations'],
    };
}

