/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Sankey diagram node model.
 * @export
 * @interface SankeyNode
 */
export interface SankeyNode {
    /**
     * Node ID
     * @type {string}
     * @memberof SankeyNode
     */
    id: string;
    /**
     * Node name
     * @type {string}
     * @memberof SankeyNode
     */
    name: string;
}

/**
 * Check if a given object implements the SankeyNode interface.
 */
export function instanceOfSankeyNode(value: object): value is SankeyNode {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SankeyNodeFromJSON(json: any): SankeyNode {
    return SankeyNodeFromJSONTyped(json, false);
}

export function SankeyNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SankeyNode {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function SankeyNodeToJSON(json: any): SankeyNode {
    return SankeyNodeToJSONTyped(json, false);
}

export function SankeyNodeToJSONTyped(value?: SankeyNode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

