/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Simulation request model.
 * @export
 * @interface SimulationRequest
 */
export interface SimulationRequest {
    /**
     * Simulation configuration
     * @type {object}
     * @memberof SimulationRequest
     */
    config: object;
}

/**
 * Check if a given object implements the SimulationRequest interface.
 */
export function instanceOfSimulationRequest(value: object): value is SimulationRequest {
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function SimulationRequestFromJSON(json: any): SimulationRequest {
    return SimulationRequestFromJSONTyped(json, false);
}

export function SimulationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'],
    };
}

export function SimulationRequestToJSON(json: any): SimulationRequest {
    return SimulationRequestToJSONTyped(json, false);
}

export function SimulationRequestToJSONTyped(value?: SimulationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
    };
}

