/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Stress test scenario model.
 * @export
 * @interface StressTestScenario
 */
export interface StressTestScenario {
    /**
     * Scenario name
     * @type {string}
     * @memberof StressTestScenario
     */
    name: string;
    /**
     * Scenario description
     * @type {string}
     * @memberof StressTestScenario
     */
    description?: string;
    /**
     * Property value shock as percentage (-1 to 1)
     * @type {number}
     * @memberof StressTestScenario
     */
    propertyValueShock: number;
    /**
     * Interest rate shock in percentage points (-0.1 to 0.1)
     * @type {number}
     * @memberof StressTestScenario
     */
    interestRateShock: number;
    /**
     * Default rate shock as multiplier (0-10)
     * @type {number}
     * @memberof StressTestScenario
     */
    defaultRateShock: number;
    /**
     * Liquidity shock as percentage of expected liquidity (0-1)
     * @type {number}
     * @memberof StressTestScenario
     */
    liquidityShock: number;
}

/**
 * Check if a given object implements the StressTestScenario interface.
 */
export function instanceOfStressTestScenario(value: object): value is StressTestScenario {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('propertyValueShock' in value) || value['propertyValueShock'] === undefined) return false;
    if (!('interestRateShock' in value) || value['interestRateShock'] === undefined) return false;
    if (!('defaultRateShock' in value) || value['defaultRateShock'] === undefined) return false;
    if (!('liquidityShock' in value) || value['liquidityShock'] === undefined) return false;
    return true;
}

export function StressTestScenarioFromJSON(json: any): StressTestScenario {
    return StressTestScenarioFromJSONTyped(json, false);
}

export function StressTestScenarioFromJSONTyped(json: any, ignoreDiscriminator: boolean): StressTestScenario {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'propertyValueShock': json['property_value_shock'],
        'interestRateShock': json['interest_rate_shock'],
        'defaultRateShock': json['default_rate_shock'],
        'liquidityShock': json['liquidity_shock'],
    };
}

export function StressTestScenarioToJSON(json: any): StressTestScenario {
    return StressTestScenarioToJSONTyped(json, false);
}

export function StressTestScenarioToJSONTyped(value?: StressTestScenario | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'property_value_shock': value['propertyValueShock'],
        'interest_rate_shock': value['interestRateShock'],
        'default_rate_shock': value['defaultRateShock'],
        'liquidity_shock': value['liquidityShock'],
    };
}

