/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaxCashflow } from './TaxCashflow';
import {
    TaxCashflowFromJSON,
    TaxCashflowFromJSONTyped,
    TaxCashflowToJSON,
    TaxCashflowToJSONTyped,
} from './TaxCashflow';
import type { TaxMetrics } from './TaxMetrics';
import {
    TaxMetricsFromJSON,
    TaxMetricsFromJSONTyped,
    TaxMetricsToJSON,
    TaxMetricsToJSONTyped,
} from './TaxMetrics';

/**
 * Tax impact analysis model.
 * @export
 * @interface TaxImpactAnalysis
 */
export interface TaxImpactAnalysis {
    /**
     * Pre-tax cashflows by year
     * @type {Array<TaxCashflow>}
     * @memberof TaxImpactAnalysis
     */
    preTaxCashflows: Array<TaxCashflow>;
    /**
     * Post-tax cashflows by year
     * @type {Array<TaxCashflow>}
     * @memberof TaxImpactAnalysis
     */
    postTaxCashflows: Array<TaxCashflow>;
    /**
     * Tax metrics
     * @type {TaxMetrics}
     * @memberof TaxImpactAnalysis
     */
    taxMetrics: TaxMetrics;
}

/**
 * Check if a given object implements the TaxImpactAnalysis interface.
 */
export function instanceOfTaxImpactAnalysis(value: object): value is TaxImpactAnalysis {
    if (!('preTaxCashflows' in value) || value['preTaxCashflows'] === undefined) return false;
    if (!('postTaxCashflows' in value) || value['postTaxCashflows'] === undefined) return false;
    if (!('taxMetrics' in value) || value['taxMetrics'] === undefined) return false;
    return true;
}

export function TaxImpactAnalysisFromJSON(json: any): TaxImpactAnalysis {
    return TaxImpactAnalysisFromJSONTyped(json, false);
}

export function TaxImpactAnalysisFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxImpactAnalysis {
    if (json == null) {
        return json;
    }
    return {
        
        'preTaxCashflows': ((json['pre_tax_cashflows'] as Array<any>).map(TaxCashflowFromJSON)),
        'postTaxCashflows': ((json['post_tax_cashflows'] as Array<any>).map(TaxCashflowFromJSON)),
        'taxMetrics': TaxMetricsFromJSON(json['tax_metrics']),
    };
}

export function TaxImpactAnalysisToJSON(json: any): TaxImpactAnalysis {
    return TaxImpactAnalysisToJSONTyped(json, false);
}

export function TaxImpactAnalysisToJSONTyped(value?: TaxImpactAnalysis | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pre_tax_cashflows': ((value['preTaxCashflows'] as Array<any>).map(TaxCashflowToJSON)),
        'post_tax_cashflows': ((value['postTaxCashflows'] as Array<any>).map(TaxCashflowToJSON)),
        'tax_metrics': TaxMetricsToJSON(value['taxMetrics']),
    };
}

