/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Tornado chart item model.
 * @export
 * @interface TornadoChartItem
 */
export interface TornadoChartItem {
    /**
     * Parameter name
     * @type {string}
     * @memberof TornadoChartItem
     */
    parameter: string;
    /**
     * Low parameter value
     * @type {number}
     * @memberof TornadoChartItem
     */
    lowValue: number;
    /**
     * High parameter value
     * @type {number}
     * @memberof TornadoChartItem
     */
    highValue: number;
    /**
     * Metric value at low parameter value
     * @type {number}
     * @memberof TornadoChartItem
     */
    lowMetric: number;
    /**
     * Metric value at high parameter value
     * @type {number}
     * @memberof TornadoChartItem
     */
    highMetric: number;
    /**
     * Metric value at base parameter value
     * @type {number}
     * @memberof TornadoChartItem
     */
    baseMetric: number;
    /**
     * Metric name
     * @type {string}
     * @memberof TornadoChartItem
     */
    metricName: string;
}

/**
 * Check if a given object implements the TornadoChartItem interface.
 */
export function instanceOfTornadoChartItem(value: object): value is TornadoChartItem {
    if (!('parameter' in value) || value['parameter'] === undefined) return false;
    if (!('lowValue' in value) || value['lowValue'] === undefined) return false;
    if (!('highValue' in value) || value['highValue'] === undefined) return false;
    if (!('lowMetric' in value) || value['lowMetric'] === undefined) return false;
    if (!('highMetric' in value) || value['highMetric'] === undefined) return false;
    if (!('baseMetric' in value) || value['baseMetric'] === undefined) return false;
    if (!('metricName' in value) || value['metricName'] === undefined) return false;
    return true;
}

export function TornadoChartItemFromJSON(json: any): TornadoChartItem {
    return TornadoChartItemFromJSONTyped(json, false);
}

export function TornadoChartItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TornadoChartItem {
    if (json == null) {
        return json;
    }
    return {
        
        'parameter': json['parameter'],
        'lowValue': json['low_value'],
        'highValue': json['high_value'],
        'lowMetric': json['low_metric'],
        'highMetric': json['high_metric'],
        'baseMetric': json['base_metric'],
        'metricName': json['metric_name'],
    };
}

export function TornadoChartItemToJSON(json: any): TornadoChartItem {
    return TornadoChartItemToJSONTyped(json, false);
}

export function TornadoChartItemToJSONTyped(value?: TornadoChartItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parameter': value['parameter'],
        'low_value': value['lowValue'],
        'high_value': value['highValue'],
        'low_metric': value['lowMetric'],
        'high_metric': value['highMetric'],
        'base_metric': value['baseMetric'],
        'metric_name': value['metricName'],
    };
}

