# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class CashReserveMetricsResponse(BaseModel):
    """
    Cash reserve metrics response model.
    """ # noqa: E501
    avg_cash_reserve: Union[StrictFloat, StrictInt] = Field(description="Average cash reserve")
    min_cash_reserve: Union[StrictFloat, StrictInt] = Field(description="Minimum cash reserve")
    max_cash_reserve: Union[StrictFloat, StrictInt] = Field(description="Maximum cash reserve")
    avg_cash_reserve_pct: Union[StrictFloat, StrictInt] = Field(description="Average cash reserve as percentage of fund size")
    min_cash_reserve_pct: Union[StrictFloat, StrictInt] = Field(description="Minimum cash reserve as percentage of fund size")
    max_cash_reserve_pct: Union[StrictFloat, StrictInt] = Field(description="Maximum cash reserve as percentage of fund size")
    __properties: ClassVar[List[str]] = ["avg_cash_reserve", "min_cash_reserve", "max_cash_reserve", "avg_cash_reserve_pct", "min_cash_reserve_pct", "max_cash_reserve_pct"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CashReserveMetricsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CashReserveMetricsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "avg_cash_reserve": obj.get("avg_cash_reserve"),
            "min_cash_reserve": obj.get("min_cash_reserve"),
            "max_cash_reserve": obj.get("max_cash_reserve"),
            "avg_cash_reserve_pct": obj.get("avg_cash_reserve_pct"),
            "min_cash_reserve_pct": obj.get("min_cash_reserve_pct"),
            "max_cash_reserve_pct": obj.get("max_cash_reserve_pct")
        })
        return _obj


