# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class PerformanceMetrics(BaseModel):
    """
    Performance/return-risk metrics model.
    """ # noqa: E501
    net_irr: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Net-IRR point value")
    sharpe_ratio: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Sharpe ratio")
    sortino_ratio: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Sortino ratio")
    hurdle_clear_probability: Dict[str, Any] = Field(description="Hurdle-clear probability")
    calmar_ratio: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Calmar ratio")
    information_ratio: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Information ratio")
    treynor_ratio: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Treynor ratio")
    omega_ratio: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Omega ratio")
    kappa_ratio: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Kappa ratio")
    gain_loss_ratio: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Gain-Loss ratio")
    __properties: ClassVar[List[str]] = ["net_irr", "sharpe_ratio", "sortino_ratio", "hurdle_clear_probability", "calmar_ratio", "information_ratio", "treynor_ratio", "omega_ratio", "kappa_ratio", "gain_loss_ratio"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PerformanceMetrics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PerformanceMetrics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "net_irr": obj.get("net_irr"),
            "sharpe_ratio": obj.get("sharpe_ratio"),
            "sortino_ratio": obj.get("sortino_ratio"),
            "hurdle_clear_probability": obj.get("hurdle_clear_probability"),
            "calmar_ratio": obj.get("calmar_ratio"),
            "information_ratio": obj.get("information_ratio"),
            "treynor_ratio": obj.get("treynor_ratio"),
            "omega_ratio": obj.get("omega_ratio"),
            "kappa_ratio": obj.get("kappa_ratio"),
            "gain_loss_ratio": obj.get("gain_loss_ratio")
        })
        return _obj


