# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class ReinvestmentTablesResponse(BaseModel):
    """
    Reinvestment tables response model.
    """ # noqa: E501
    reinvestment_summary_table: List[Dict[str, Any]] = Field(description="Reinvestment summary table")
    reinvestment_events_table: List[Dict[str, Any]] = Field(description="Reinvestment events table")
    reinvestment_loans_table: List[Dict[str, Any]] = Field(description="Reinvestment loans table")
    cash_reserve_metrics_table: List[Dict[str, Any]] = Field(description="Cash reserve metrics table")
    __properties: ClassVar[List[str]] = ["reinvestment_summary_table", "reinvestment_events_table", "reinvestment_loans_table", "cash_reserve_metrics_table"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReinvestmentTablesResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReinvestmentTablesResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "reinvestment_summary_table": obj.get("reinvestment_summary_table"),
            "reinvestment_events_table": obj.get("reinvestment_events_table"),
            "reinvestment_loans_table": obj.get("reinvestment_loans_table"),
            "cash_reserve_metrics_table": obj.get("cash_reserve_metrics_table")
        })
        return _obj


