# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from equihome_sim_sdk.models.parameter_variation import ParameterVariation
from equihome_sim_sdk.models.tornado_chart_item import TornadoChartItem
from typing import Optional, Set
from typing_extensions import Self

class SensitivityAnalysis(BaseModel):
    """
    Sensitivity analysis model.
    """ # noqa: E501
    parameter_variations: List[ParameterVariation] = Field(description="Parameter variations")
    tornado_chart: List[TornadoChartItem] = Field(description="Tornado chart data")
    __properties: ClassVar[List[str]] = ["parameter_variations", "tornado_chart"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SensitivityAnalysis from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in parameter_variations (list)
        _items = []
        if self.parameter_variations:
            for _item_parameter_variations in self.parameter_variations:
                if _item_parameter_variations:
                    _items.append(_item_parameter_variations.to_dict())
            _dict['parameter_variations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tornado_chart (list)
        _items = []
        if self.tornado_chart:
            for _item_tornado_chart in self.tornado_chart:
                if _item_tornado_chart:
                    _items.append(_item_tornado_chart.to_dict())
            _dict['tornado_chart'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SensitivityAnalysis from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "parameter_variations": [ParameterVariation.from_dict(_item) for _item in obj["parameter_variations"]] if obj.get("parameter_variations") is not None else None,
            "tornado_chart": [TornadoChartItem.from_dict(_item) for _item in obj["tornado_chart"]] if obj.get("tornado_chart") is not None else None
        })
        return _obj


