# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from equihome_sim_sdk.models.tax_cashflow import TaxCashflow
from equihome_sim_sdk.models.tax_metrics import TaxMetrics
from typing import Optional, Set
from typing_extensions import Self

class TaxImpactAnalysis(BaseModel):
    """
    Tax impact analysis model.
    """ # noqa: E501
    pre_tax_cashflows: List[TaxCashflow] = Field(description="Pre-tax cashflows by year")
    post_tax_cashflows: List[TaxCashflow] = Field(description="Post-tax cashflows by year")
    tax_metrics: TaxMetrics = Field(description="Tax metrics")
    __properties: ClassVar[List[str]] = ["pre_tax_cashflows", "post_tax_cashflows", "tax_metrics"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TaxImpactAnalysis from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in pre_tax_cashflows (list)
        _items = []
        if self.pre_tax_cashflows:
            for _item_pre_tax_cashflows in self.pre_tax_cashflows:
                if _item_pre_tax_cashflows:
                    _items.append(_item_pre_tax_cashflows.to_dict())
            _dict['pre_tax_cashflows'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in post_tax_cashflows (list)
        _items = []
        if self.post_tax_cashflows:
            for _item_post_tax_cashflows in self.post_tax_cashflows:
                if _item_post_tax_cashflows:
                    _items.append(_item_post_tax_cashflows.to_dict())
            _dict['post_tax_cashflows'] = _items
        # override the default output from pydantic by calling `to_dict()` of tax_metrics
        if self.tax_metrics:
            _dict['tax_metrics'] = self.tax_metrics.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TaxImpactAnalysis from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pre_tax_cashflows": [TaxCashflow.from_dict(_item) for _item in obj["pre_tax_cashflows"]] if obj.get("pre_tax_cashflows") is not None else None,
            "post_tax_cashflows": [TaxCashflow.from_dict(_item) for _item in obj["post_tax_cashflows"]] if obj.get("post_tax_cashflows") is not None else None,
            "tax_metrics": TaxMetrics.from_dict(obj["tax_metrics"]) if obj.get("tax_metrics") is not None else None
        })
        return _obj


