# coding: utf-8

"""
    EQU IHOME SIM ENGINE API

    API for running home equity investment fund simulations

    The version of the OpenAPI document: 0.1.0
    Contact: info@equihome.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class TrancheCashflowResponse(BaseModel):
    """
    Tranche cashflow response model.
    """ # noqa: E501
    year: Union[StrictFloat, StrictInt] = Field(description="Year")
    month: Optional[StrictInt] = Field(default=None, description="Month (if applicable)")
    quarter: Optional[StrictInt] = Field(default=None, description="Quarter (if applicable)")
    principal_payment: Union[StrictFloat, StrictInt] = Field(description="Principal payment")
    interest_payment: Union[StrictFloat, StrictInt] = Field(description="Interest payment")
    profit_share_payment: Union[StrictFloat, StrictInt] = Field(description="Profit share payment")
    total_payment: Union[StrictFloat, StrictInt] = Field(description="Total payment")
    remaining_principal: Union[StrictFloat, StrictInt] = Field(description="Remaining principal")
    __properties: ClassVar[List[str]] = ["year", "month", "quarter", "principal_payment", "interest_payment", "profit_share_payment", "total_payment", "remaining_principal"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrancheCashflowResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrancheCashflowResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "year": obj.get("year"),
            "month": obj.get("month"),
            "quarter": obj.get("quarter"),
            "principal_payment": obj.get("principal_payment"),
            "interest_payment": obj.get("interest_payment"),
            "profit_share_payment": obj.get("profit_share_payment"),
            "total_payment": obj.get("total_payment"),
            "remaining_principal": obj.get("remaining_principal")
        })
        return _obj


