name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Lint with ruff
        run: |
          poetry run ruff check .
      - name: Check formatting with black
        run: |
          poetry run black --check .
      - name: Type check with mypy
        run: |
          poetry run mypy .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run fast tests
        run: |
          poetry run pytest -v -k "not slow"
      - name: Run slow tests
        run: |
          poetry run pytest -v -k "slow"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Build package
        run: |
          poetry build
      - name: Build Docker image
        run: |
          docker build -t equ-ihome-sim-engine:latest .
