/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Cashflow heatmap item model.
 * @export
 * @interface CashflowHeatmapItem
 */
export interface CashflowHeatmapItem {
    /**
     * Year
     * @type {number}
     * @memberof CashflowHeatmapItem
     */
    year: number;
    /**
     * Month
     * @type {number}
     * @memberof CashflowHeatmapItem
     */
    month: number;
    /**
     * Cashflow category
     * @type {string}
     * @memberof CashflowHeatmapItem
     */
    category: string;
    /**
     * Cashflow amount
     * @type {number}
     * @memberof CashflowHeatmapItem
     */
    amount: number;
}

/**
 * Check if a given object implements the CashflowHeatmapItem interface.
 */
export function instanceOfCashflowHeatmapItem(value: object): value is CashflowHeatmapItem {
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('month' in value) || value['month'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function CashflowHeatmapItemFromJSON(json: any): CashflowHeatmapItem {
    return CashflowHeatmapItemFromJSONTyped(json, false);
}

export function CashflowHeatmapItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashflowHeatmapItem {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'],
        'month': json['month'],
        'category': json['category'],
        'amount': json['amount'],
    };
}

export function CashflowHeatmapItemToJSON(json: any): CashflowHeatmapItem {
    return CashflowHeatmapItemToJSONTyped(json, false);
}

export function CashflowHeatmapItemToJSONTyped(value?: CashflowHeatmapItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'month': value['month'],
        'category': value['category'],
        'amount': value['amount'],
    };
}

