/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Cashflow waterfall item model.
 * @export
 * @interface CashflowWaterfallItem
 */
export interface CashflowWaterfallItem {
    /**
     * Cashflow category
     * @type {string}
     * @memberof CashflowWaterfallItem
     */
    category: string;
    /**
     * Cashflow amount
     * @type {number}
     * @memberof CashflowWaterfallItem
     */
    amount: number;
}

/**
 * Check if a given object implements the CashflowWaterfallItem interface.
 */
export function instanceOfCashflowWaterfallItem(value: object): value is CashflowWaterfallItem {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function CashflowWaterfallItemFromJSON(json: any): CashflowWaterfallItem {
    return CashflowWaterfallItemFromJSONTyped(json, false);
}

export function CashflowWaterfallItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashflowWaterfallItem {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'],
        'amount': json['amount'],
    };
}

export function CashflowWaterfallItemToJSON(json: any): CashflowWaterfallItem {
    return CashflowWaterfallItemToJSONTyped(json, false);
}

export function CashflowWaterfallItemToJSONTyped(value?: CashflowWaterfallItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'amount': value['amount'],
    };
}

