/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Credit metrics model.
 * @export
 * @interface CreditMetrics
 */
export interface CreditMetrics {
    /**
     * Current LTV metrics
     * @type {object}
     * @memberof CreditMetrics
     */
    currentLtv: object;
    /**
     * Stress LTV metrics with -20% price shock
     * @type {object}
     * @memberof CreditMetrics
     */
    stressLtv: object;
    /**
     * Default probability metrics
     * @type {object}
     * @memberof CreditMetrics
     */
    defaultProbability: object;
    /**
     * Portfolio default rate (exposure-weighted PD)
     * @type {number}
     * @memberof CreditMetrics
     */
    portfolioDefaultRate: number;
}

/**
 * Check if a given object implements the CreditMetrics interface.
 */
export function instanceOfCreditMetrics(value: object): value is CreditMetrics {
    if (!('currentLtv' in value) || value['currentLtv'] === undefined) return false;
    if (!('stressLtv' in value) || value['stressLtv'] === undefined) return false;
    if (!('defaultProbability' in value) || value['defaultProbability'] === undefined) return false;
    if (!('portfolioDefaultRate' in value) || value['portfolioDefaultRate'] === undefined) return false;
    return true;
}

export function CreditMetricsFromJSON(json: any): CreditMetrics {
    return CreditMetricsFromJSONTyped(json, false);
}

export function CreditMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'currentLtv': json['current_ltv'],
        'stressLtv': json['stress_ltv'],
        'defaultProbability': json['default_probability'],
        'portfolioDefaultRate': json['portfolio_default_rate'],
    };
}

export function CreditMetricsToJSON(json: any): CreditMetrics {
    return CreditMetricsToJSONTyped(json, false);
}

export function CreditMetricsToJSONTyped(value?: CreditMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_ltv': value['currentLtv'],
        'stress_ltv': value['stressLtv'],
        'default_probability': value['defaultProbability'],
        'portfolio_default_rate': value['portfolioDefaultRate'],
    };
}

