/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Enhanced exit scenario request model.
 * @export
 * @interface EnhancedExitScenarioRequest
 */
export interface EnhancedExitScenarioRequest {
    /**
     * Base annual exit probability
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    baseExitRate?: number;
    /**
     * Weight for time-based exit probability
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    timeFactor?: number;
    /**
     * Weight for price-based exit probability
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    priceFactor?: number;
    /**
     * Minimum holding period in years
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    minHoldPeriod?: number;
    /**
     * Maximum holding period in years
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    maxHoldPeriod?: number;
    /**
     * Base weight for sale exits
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    saleWeight?: number;
    /**
     * Base weight for refinance exits
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    refinanceWeight?: number;
    /**
     * Base weight for default exits
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    defaultWeight?: number;
    /**
     * Fund's share of appreciation
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    appreciationShare?: number;
    /**
     * How sensitive refinancing is to interest rate changes
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    refinanceInterestRateSensitivity?: number;
    /**
     * How sensitive sales are to appreciation
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    saleAppreciationSensitivity?: number;
    /**
     * Annual probability of life events triggering exits
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    lifeEventProbability?: number;
    /**
     * Correlation in exit decisions (herd behavior)
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    behavioralCorrelation?: number;
    /**
     * How much recessions increase defaults
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    recessionDefaultMultiplier?: number;
    /**
     * How inflation affects refinancing
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    inflationRefinanceMultiplier?: number;
    /**
     * How employment affects exits
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    employmentSensitivity?: number;
    /**
     * How population migration affects exits
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    migrationSensitivity?: number;
    /**
     * Compliance cost as percentage of loan
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    regulatoryComplianceCost?: number;
    /**
     * Tax efficiency factor (1.0 = fully efficient)
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    taxEfficiencyFactor?: number;
    /**
     * Whether to segment by vintage
     * @type {boolean}
     * @memberof EnhancedExitScenarioRequest
     */
    vintageSegmentation?: boolean;
    /**
     * Whether to segment by LTV
     * @type {boolean}
     * @memberof EnhancedExitScenarioRequest
     */
    ltvSegmentation?: boolean;
    /**
     * Whether to segment by zone
     * @type {boolean}
     * @memberof EnhancedExitScenarioRequest
     */
    zoneSegmentation?: boolean;
    /**
     * Confidence level for Value-at-Risk
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    varConfidenceLevel?: number;
    /**
     * Severity of stress tests (0-1)
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    stressTestSeverity?: number;
    /**
     * Threshold for tail risk events
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    tailRiskThreshold?: number;
    /**
     * Whether to use machine learning models
     * @type {boolean}
     * @memberof EnhancedExitScenarioRequest
     */
    useMlModels?: boolean;
    /**
     * Threshold for important features
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    featureImportanceThreshold?: number;
    /**
     * Standard deviations for anomaly detection
     * @type {number}
     * @memberof EnhancedExitScenarioRequest
     */
    anomalyDetectionThreshold?: number;
}

/**
 * Check if a given object implements the EnhancedExitScenarioRequest interface.
 */
export function instanceOfEnhancedExitScenarioRequest(value: object): value is EnhancedExitScenarioRequest {
    return true;
}

export function EnhancedExitScenarioRequestFromJSON(json: any): EnhancedExitScenarioRequest {
    return EnhancedExitScenarioRequestFromJSONTyped(json, false);
}

export function EnhancedExitScenarioRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnhancedExitScenarioRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'baseExitRate': json['base_exit_rate'] == null ? undefined : json['base_exit_rate'],
        'timeFactor': json['time_factor'] == null ? undefined : json['time_factor'],
        'priceFactor': json['price_factor'] == null ? undefined : json['price_factor'],
        'minHoldPeriod': json['min_hold_period'] == null ? undefined : json['min_hold_period'],
        'maxHoldPeriod': json['max_hold_period'] == null ? undefined : json['max_hold_period'],
        'saleWeight': json['sale_weight'] == null ? undefined : json['sale_weight'],
        'refinanceWeight': json['refinance_weight'] == null ? undefined : json['refinance_weight'],
        'defaultWeight': json['default_weight'] == null ? undefined : json['default_weight'],
        'appreciationShare': json['appreciation_share'] == null ? undefined : json['appreciation_share'],
        'refinanceInterestRateSensitivity': json['refinance_interest_rate_sensitivity'] == null ? undefined : json['refinance_interest_rate_sensitivity'],
        'saleAppreciationSensitivity': json['sale_appreciation_sensitivity'] == null ? undefined : json['sale_appreciation_sensitivity'],
        'lifeEventProbability': json['life_event_probability'] == null ? undefined : json['life_event_probability'],
        'behavioralCorrelation': json['behavioral_correlation'] == null ? undefined : json['behavioral_correlation'],
        'recessionDefaultMultiplier': json['recession_default_multiplier'] == null ? undefined : json['recession_default_multiplier'],
        'inflationRefinanceMultiplier': json['inflation_refinance_multiplier'] == null ? undefined : json['inflation_refinance_multiplier'],
        'employmentSensitivity': json['employment_sensitivity'] == null ? undefined : json['employment_sensitivity'],
        'migrationSensitivity': json['migration_sensitivity'] == null ? undefined : json['migration_sensitivity'],
        'regulatoryComplianceCost': json['regulatory_compliance_cost'] == null ? undefined : json['regulatory_compliance_cost'],
        'taxEfficiencyFactor': json['tax_efficiency_factor'] == null ? undefined : json['tax_efficiency_factor'],
        'vintageSegmentation': json['vintage_segmentation'] == null ? undefined : json['vintage_segmentation'],
        'ltvSegmentation': json['ltv_segmentation'] == null ? undefined : json['ltv_segmentation'],
        'zoneSegmentation': json['zone_segmentation'] == null ? undefined : json['zone_segmentation'],
        'varConfidenceLevel': json['var_confidence_level'] == null ? undefined : json['var_confidence_level'],
        'stressTestSeverity': json['stress_test_severity'] == null ? undefined : json['stress_test_severity'],
        'tailRiskThreshold': json['tail_risk_threshold'] == null ? undefined : json['tail_risk_threshold'],
        'useMlModels': json['use_ml_models'] == null ? undefined : json['use_ml_models'],
        'featureImportanceThreshold': json['feature_importance_threshold'] == null ? undefined : json['feature_importance_threshold'],
        'anomalyDetectionThreshold': json['anomaly_detection_threshold'] == null ? undefined : json['anomaly_detection_threshold'],
    };
}

export function EnhancedExitScenarioRequestToJSON(json: any): EnhancedExitScenarioRequest {
    return EnhancedExitScenarioRequestToJSONTyped(json, false);
}

export function EnhancedExitScenarioRequestToJSONTyped(value?: EnhancedExitScenarioRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base_exit_rate': value['baseExitRate'],
        'time_factor': value['timeFactor'],
        'price_factor': value['priceFactor'],
        'min_hold_period': value['minHoldPeriod'],
        'max_hold_period': value['maxHoldPeriod'],
        'sale_weight': value['saleWeight'],
        'refinance_weight': value['refinanceWeight'],
        'default_weight': value['defaultWeight'],
        'appreciation_share': value['appreciationShare'],
        'refinance_interest_rate_sensitivity': value['refinanceInterestRateSensitivity'],
        'sale_appreciation_sensitivity': value['saleAppreciationSensitivity'],
        'life_event_probability': value['lifeEventProbability'],
        'behavioral_correlation': value['behavioralCorrelation'],
        'recession_default_multiplier': value['recessionDefaultMultiplier'],
        'inflation_refinance_multiplier': value['inflationRefinanceMultiplier'],
        'employment_sensitivity': value['employmentSensitivity'],
        'migration_sensitivity': value['migrationSensitivity'],
        'regulatory_compliance_cost': value['regulatoryComplianceCost'],
        'tax_efficiency_factor': value['taxEfficiencyFactor'],
        'vintage_segmentation': value['vintageSegmentation'],
        'ltv_segmentation': value['ltvSegmentation'],
        'zone_segmentation': value['zoneSegmentation'],
        'var_confidence_level': value['varConfidenceLevel'],
        'stress_test_severity': value['stressTestSeverity'],
        'tail_risk_threshold': value['tailRiskThreshold'],
        'use_ml_models': value['useMlModels'],
        'feature_importance_threshold': value['featureImportanceThreshold'],
        'anomaly_detection_threshold': value['anomalyDetectionThreshold'],
    };
}

