/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Exit visualization response model.
 * @export
 * @interface ExitVisualizationResponse
 */
export interface ExitVisualizationResponse {
    /**
     * Exit timing distribution chart
     * @type {Array<object>}
     * @memberof ExitVisualizationResponse
     */
    exitTimingChart: Array<object>;
    /**
     * Exit type distribution chart
     * @type {Array<object>}
     * @memberof ExitVisualizationResponse
     */
    exitTypeChart: Array<object>;
    /**
     * Cumulative exits chart
     * @type {Array<object>}
     * @memberof ExitVisualizationResponse
     */
    cumulativeExitsChart: Array<object>;
    /**
     * Exit ROI distribution chart
     * @type {Array<object>}
     * @memberof ExitVisualizationResponse
     */
    exitRoiChart: Array<object>;
    /**
     * Exit type ROI chart
     * @type {Array<object>}
     * @memberof ExitVisualizationResponse
     */
    exitTypeRoiChart: Array<object>;
    /**
     * Exit summary
     * @type {object}
     * @memberof ExitVisualizationResponse
     */
    exitSummary: object;
    /**
     * Exit value by year chart
     * @type {Array<object>}
     * @memberof ExitVisualizationResponse
     */
    exitValueByYearChart: Array<object>;
    /**
     * Exit count by year chart
     * @type {Array<object>}
     * @memberof ExitVisualizationResponse
     */
    exitCountByYearChart: Array<object>;
}

/**
 * Check if a given object implements the ExitVisualizationResponse interface.
 */
export function instanceOfExitVisualizationResponse(value: object): value is ExitVisualizationResponse {
    if (!('exitTimingChart' in value) || value['exitTimingChart'] === undefined) return false;
    if (!('exitTypeChart' in value) || value['exitTypeChart'] === undefined) return false;
    if (!('cumulativeExitsChart' in value) || value['cumulativeExitsChart'] === undefined) return false;
    if (!('exitRoiChart' in value) || value['exitRoiChart'] === undefined) return false;
    if (!('exitTypeRoiChart' in value) || value['exitTypeRoiChart'] === undefined) return false;
    if (!('exitSummary' in value) || value['exitSummary'] === undefined) return false;
    if (!('exitValueByYearChart' in value) || value['exitValueByYearChart'] === undefined) return false;
    if (!('exitCountByYearChart' in value) || value['exitCountByYearChart'] === undefined) return false;
    return true;
}

export function ExitVisualizationResponseFromJSON(json: any): ExitVisualizationResponse {
    return ExitVisualizationResponseFromJSONTyped(json, false);
}

export function ExitVisualizationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExitVisualizationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'exitTimingChart': json['exit_timing_chart'],
        'exitTypeChart': json['exit_type_chart'],
        'cumulativeExitsChart': json['cumulative_exits_chart'],
        'exitRoiChart': json['exit_roi_chart'],
        'exitTypeRoiChart': json['exit_type_roi_chart'],
        'exitSummary': json['exit_summary'],
        'exitValueByYearChart': json['exit_value_by_year_chart'],
        'exitCountByYearChart': json['exit_count_by_year_chart'],
    };
}

export function ExitVisualizationResponseToJSON(json: any): ExitVisualizationResponse {
    return ExitVisualizationResponseToJSONTyped(json, false);
}

export function ExitVisualizationResponseToJSONTyped(value?: ExitVisualizationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'exit_timing_chart': value['exitTimingChart'],
        'exit_type_chart': value['exitTypeChart'],
        'cumulative_exits_chart': value['cumulativeExitsChart'],
        'exit_roi_chart': value['exitRoiChart'],
        'exit_type_roi_chart': value['exitTypeRoiChart'],
        'exit_summary': value['exitSummary'],
        'exit_value_by_year_chart': value['exitValueByYearChart'],
        'exit_count_by_year_chart': value['exitCountByYearChart'],
    };
}

