/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Leverage event model.
 * @export
 * @interface LeverageEvent
 */
export interface LeverageEvent {
    /**
     * Facility ID
     * @type {string}
     * @memberof LeverageEvent
     */
    facilityId: string;
    /**
     * Date of the event
     * @type {string}
     * @memberof LeverageEvent
     */
    date: string;
    /**
     * Amount of the event
     * @type {number}
     * @memberof LeverageEvent
     */
    amount: number;
    /**
     * Simulation year
     * @type {number}
     * @memberof LeverageEvent
     */
    year: number;
    /**
     * Month (1-12)
     * @type {number}
     * @memberof LeverageEvent
     */
    month: number;
    /**
     * Event type (draw, repayment, interest, fee)
     * @type {string}
     * @memberof LeverageEvent
     */
    eventType: string;
    /**
     * Additional details
     * @type {object}
     * @memberof LeverageEvent
     */
    details?: object;
}

/**
 * Check if a given object implements the LeverageEvent interface.
 */
export function instanceOfLeverageEvent(value: object): value is LeverageEvent {
    if (!('facilityId' in value) || value['facilityId'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('month' in value) || value['month'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    return true;
}

export function LeverageEventFromJSON(json: any): LeverageEvent {
    return LeverageEventFromJSONTyped(json, false);
}

export function LeverageEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeverageEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'facilityId': json['facility_id'],
        'date': json['date'],
        'amount': json['amount'],
        'year': json['year'],
        'month': json['month'],
        'eventType': json['event_type'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function LeverageEventToJSON(json: any): LeverageEvent {
    return LeverageEventToJSONTyped(json, false);
}

export function LeverageEventToJSONTyped(value?: LeverageEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'facility_id': value['facilityId'],
        'date': value['date'],
        'amount': value['amount'],
        'year': value['year'],
        'month': value['month'],
        'event_type': value['eventType'],
        'details': value['details'],
    };
}

