/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Metrics by year model.
 * @export
 * @interface MetricsByYear
 */
export interface MetricsByYear {
    /**
     * Year
     * @type {number}
     * @memberof MetricsByYear
     */
    year: number;
    /**
     * Distributions to Paid-In
     * @type {number}
     * @memberof MetricsByYear
     */
    dpi: number;
    /**
     * Residual Value to Paid-In
     * @type {number}
     * @memberof MetricsByYear
     */
    rvpi: number;
    /**
     * Total Value to Paid-In
     * @type {number}
     * @memberof MetricsByYear
     */
    tvpi: number;
    /**
     * Internal Rate of Return
     * @type {number}
     * @memberof MetricsByYear
     */
    irr: number;
    /**
     * Cash yield
     * @type {number}
     * @memberof MetricsByYear
     */
    cashYield: number;
}

/**
 * Check if a given object implements the MetricsByYear interface.
 */
export function instanceOfMetricsByYear(value: object): value is MetricsByYear {
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('dpi' in value) || value['dpi'] === undefined) return false;
    if (!('rvpi' in value) || value['rvpi'] === undefined) return false;
    if (!('tvpi' in value) || value['tvpi'] === undefined) return false;
    if (!('irr' in value) || value['irr'] === undefined) return false;
    if (!('cashYield' in value) || value['cashYield'] === undefined) return false;
    return true;
}

export function MetricsByYearFromJSON(json: any): MetricsByYear {
    return MetricsByYearFromJSONTyped(json, false);
}

export function MetricsByYearFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricsByYear {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'],
        'dpi': json['dpi'],
        'rvpi': json['rvpi'],
        'tvpi': json['tvpi'],
        'irr': json['irr'],
        'cashYield': json['cash_yield'],
    };
}

export function MetricsByYearToJSON(json: any): MetricsByYear {
    return MetricsByYearToJSONTyped(json, false);
}

export function MetricsByYearToJSONTyped(value?: MetricsByYear | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'dpi': value['dpi'],
        'rvpi': value['rvpi'],
        'tvpi': value['tvpi'],
        'irr': value['irr'],
        'cash_yield': value['cashYield'],
    };
}

