/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Performance report request model.
 * 
 * Attributes:
 *     simulation_id: Simulation ID
 *     include_kpi_table: Whether to include KPI table in the report
 *     include_zone_allocation: Whether to include zone allocation in the report
 *     include_cash_flow: Whether to include cash flow in the report
 *     include_risk_metrics: Whether to include risk metrics in the report
 *     include_tranche_performance: Whether to include tranche performance in the report
 *     include_loan_performance: Whether to include loan performance in the report
 *     include_visualization: Whether to include visualization data in the report
 *     export_format: Format to export the report to
 *     export_path: Path to export the report to
 * @export
 * @interface PerformanceReportRequest
 */
export interface PerformanceReportRequest {
    /**
     * Simulation ID
     * @type {string}
     * @memberof PerformanceReportRequest
     */
    simulationId: string;
    /**
     * Whether to include KPI table in the report
     * @type {boolean}
     * @memberof PerformanceReportRequest
     */
    includeKpiTable?: boolean;
    /**
     * Whether to include zone allocation in the report
     * @type {boolean}
     * @memberof PerformanceReportRequest
     */
    includeZoneAllocation?: boolean;
    /**
     * Whether to include cash flow in the report
     * @type {boolean}
     * @memberof PerformanceReportRequest
     */
    includeCashFlow?: boolean;
    /**
     * Whether to include risk metrics in the report
     * @type {boolean}
     * @memberof PerformanceReportRequest
     */
    includeRiskMetrics?: boolean;
    /**
     * Whether to include tranche performance in the report
     * @type {boolean}
     * @memberof PerformanceReportRequest
     */
    includeTranchePerformance?: boolean;
    /**
     * Whether to include loan performance in the report
     * @type {boolean}
     * @memberof PerformanceReportRequest
     */
    includeLoanPerformance?: boolean;
    /**
     * Whether to include visualization data in the report
     * @type {boolean}
     * @memberof PerformanceReportRequest
     */
    includeVisualization?: boolean;
    /**
     * Format to export the report to (json, csv, excel, markdown, html)
     * @type {string}
     * @memberof PerformanceReportRequest
     */
    exportFormat?: string;
    /**
     * Path to export the report to
     * @type {string}
     * @memberof PerformanceReportRequest
     */
    exportPath?: string;
}

/**
 * Check if a given object implements the PerformanceReportRequest interface.
 */
export function instanceOfPerformanceReportRequest(value: object): value is PerformanceReportRequest {
    if (!('simulationId' in value) || value['simulationId'] === undefined) return false;
    return true;
}

export function PerformanceReportRequestFromJSON(json: any): PerformanceReportRequest {
    return PerformanceReportRequestFromJSONTyped(json, false);
}

export function PerformanceReportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformanceReportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'simulationId': json['simulation_id'],
        'includeKpiTable': json['include_kpi_table'] == null ? undefined : json['include_kpi_table'],
        'includeZoneAllocation': json['include_zone_allocation'] == null ? undefined : json['include_zone_allocation'],
        'includeCashFlow': json['include_cash_flow'] == null ? undefined : json['include_cash_flow'],
        'includeRiskMetrics': json['include_risk_metrics'] == null ? undefined : json['include_risk_metrics'],
        'includeTranchePerformance': json['include_tranche_performance'] == null ? undefined : json['include_tranche_performance'],
        'includeLoanPerformance': json['include_loan_performance'] == null ? undefined : json['include_loan_performance'],
        'includeVisualization': json['include_visualization'] == null ? undefined : json['include_visualization'],
        'exportFormat': json['export_format'] == null ? undefined : json['export_format'],
        'exportPath': json['export_path'] == null ? undefined : json['export_path'],
    };
}

export function PerformanceReportRequestToJSON(json: any): PerformanceReportRequest {
    return PerformanceReportRequestToJSONTyped(json, false);
}

export function PerformanceReportRequestToJSONTyped(value?: PerformanceReportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'simulation_id': value['simulationId'],
        'include_kpi_table': value['includeKpiTable'],
        'include_zone_allocation': value['includeZoneAllocation'],
        'include_cash_flow': value['includeCashFlow'],
        'include_risk_metrics': value['includeRiskMetrics'],
        'include_tranche_performance': value['includeTranchePerformance'],
        'include_loan_performance': value['includeLoanPerformance'],
        'include_visualization': value['includeVisualization'],
        'export_format': value['exportFormat'],
        'export_path': value['exportPath'],
    };
}

