/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Reinvestment performance response model.
 * @export
 * @interface ReinvestmentPerformanceResponse
 */
export interface ReinvestmentPerformanceResponse {
    /**
     * Return on investment for reinvested capital
     * @type {number}
     * @memberof ReinvestmentPerformanceResponse
     */
    roi: number;
    /**
     * Average hold period for reinvestment loans in years
     * @type {number}
     * @memberof ReinvestmentPerformanceResponse
     */
    avgHoldPeriod: number;
    /**
     * Exit type distribution for reinvestment loans
     * @type {{ [key: string]: number; }}
     * @memberof ReinvestmentPerformanceResponse
     */
    exitTypeDistribution: { [key: string]: number; };
}

/**
 * Check if a given object implements the ReinvestmentPerformanceResponse interface.
 */
export function instanceOfReinvestmentPerformanceResponse(value: object): value is ReinvestmentPerformanceResponse {
    if (!('roi' in value) || value['roi'] === undefined) return false;
    if (!('avgHoldPeriod' in value) || value['avgHoldPeriod'] === undefined) return false;
    if (!('exitTypeDistribution' in value) || value['exitTypeDistribution'] === undefined) return false;
    return true;
}

export function ReinvestmentPerformanceResponseFromJSON(json: any): ReinvestmentPerformanceResponse {
    return ReinvestmentPerformanceResponseFromJSONTyped(json, false);
}

export function ReinvestmentPerformanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReinvestmentPerformanceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'roi': json['roi'],
        'avgHoldPeriod': json['avg_hold_period'],
        'exitTypeDistribution': json['exit_type_distribution'],
    };
}

export function ReinvestmentPerformanceResponseToJSON(json: any): ReinvestmentPerformanceResponse {
    return ReinvestmentPerformanceResponseToJSONTyped(json, false);
}

export function ReinvestmentPerformanceResponseToJSONTyped(value?: ReinvestmentPerformanceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'roi': value['roi'],
        'avg_hold_period': value['avgHoldPeriod'],
        'exit_type_distribution': value['exitTypeDistribution'],
    };
}

