/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResultResponse } from './ResultResponse';
import {
    ResultResponseFromJSON,
    ResultResponseFromJSONTyped,
    ResultResponseToJSON,
    ResultResponseToJSONTyped,
} from './ResultResponse';

/**
 * Result list response model.
 * @export
 * @interface ResultListResponse
 */
export interface ResultListResponse {
    /**
     * List of results
     * @type {Array<ResultResponse>}
     * @memberof ResultListResponse
     */
    results: Array<ResultResponse>;
    /**
     * Total count
     * @type {number}
     * @memberof ResultListResponse
     */
    count: number;
    /**
     * Limit
     * @type {number}
     * @memberof ResultListResponse
     */
    limit: number;
    /**
     * Offset
     * @type {number}
     * @memberof ResultListResponse
     */
    offset: number;
}

/**
 * Check if a given object implements the ResultListResponse interface.
 */
export function instanceOfResultListResponse(value: object): value is ResultListResponse {
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function ResultListResponseFromJSON(json: any): ResultListResponse {
    return ResultListResponseFromJSONTyped(json, false);
}

export function ResultListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(ResultResponseFromJSON)),
        'count': json['count'],
        'limit': json['limit'],
        'offset': json['offset'],
    };
}

export function ResultListResponseToJSON(json: any): ResultListResponse {
    return ResultListResponseToJSONTyped(json, false);
}

export function ResultListResponseToJSONTyped(value?: ResultListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(ResultResponseToJSON)),
        'count': value['count'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

