/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Liquidity metrics model.
 * @export
 * @interface SrcApiRoutersRiskLiquidityMetrics
 */
export interface SrcApiRoutersRiskLiquidityMetrics {
    /**
     * Liquidity score metrics
     * @type {object}
     * @memberof SrcApiRoutersRiskLiquidityMetrics
     */
    liquidityScore: object;
    /**
     * Expected exit lag metrics
     * @type {object}
     * @memberof SrcApiRoutersRiskLiquidityMetrics
     */
    expectedExitLag: object;
    /**
     * Weighted Average Life (WAL)
     * @type {number}
     * @memberof SrcApiRoutersRiskLiquidityMetrics
     */
    wal: number;
    /**
     * Cash-flow-at-risk (CFaR) metrics
     * @type {object}
     * @memberof SrcApiRoutersRiskLiquidityMetrics
     */
    cfar: object;
}

/**
 * Check if a given object implements the SrcApiRoutersRiskLiquidityMetrics interface.
 */
export function instanceOfSrcApiRoutersRiskLiquidityMetrics(value: object): value is SrcApiRoutersRiskLiquidityMetrics {
    if (!('liquidityScore' in value) || value['liquidityScore'] === undefined) return false;
    if (!('expectedExitLag' in value) || value['expectedExitLag'] === undefined) return false;
    if (!('wal' in value) || value['wal'] === undefined) return false;
    if (!('cfar' in value) || value['cfar'] === undefined) return false;
    return true;
}

export function SrcApiRoutersRiskLiquidityMetricsFromJSON(json: any): SrcApiRoutersRiskLiquidityMetrics {
    return SrcApiRoutersRiskLiquidityMetricsFromJSONTyped(json, false);
}

export function SrcApiRoutersRiskLiquidityMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SrcApiRoutersRiskLiquidityMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'liquidityScore': json['liquidity_score'],
        'expectedExitLag': json['expected_exit_lag'],
        'wal': json['wal'],
        'cfar': json['cfar'],
    };
}

export function SrcApiRoutersRiskLiquidityMetricsToJSON(json: any): SrcApiRoutersRiskLiquidityMetrics {
    return SrcApiRoutersRiskLiquidityMetricsToJSONTyped(json, false);
}

export function SrcApiRoutersRiskLiquidityMetricsToJSONTyped(value?: SrcApiRoutersRiskLiquidityMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'liquidity_score': value['liquidityScore'],
        'expected_exit_lag': value['expectedExitLag'],
        'wal': value['wal'],
        'cfar': value['cfar'],
    };
}

