/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Stress test result model.
 * @export
 * @interface SrcApiRoutersRiskStressTestResult
 */
export interface SrcApiRoutersRiskStressTestResult {
    /**
     * IRR under stress scenario
     * @type {number}
     * @memberof SrcApiRoutersRiskStressTestResult
     */
    irr?: number;
    /**
     * Equity multiple under stress scenario
     * @type {number}
     * @memberof SrcApiRoutersRiskStressTestResult
     */
    equityMultiple?: number;
    /**
     * ROI under stress scenario
     * @type {number}
     * @memberof SrcApiRoutersRiskStressTestResult
     */
    roi?: number;
    /**
     * Maximum drawdown under stress scenario
     * @type {number}
     * @memberof SrcApiRoutersRiskStressTestResult
     */
    maxDrawdown?: number;
    /**
     * VaR (95%) under stress scenario
     * @type {number}
     * @memberof SrcApiRoutersRiskStressTestResult
     */
    var95?: number;
    /**
     * Percentage impact on base case IRR
     * @type {number}
     * @memberof SrcApiRoutersRiskStressTestResult
     */
    impactPct?: number;
}

/**
 * Check if a given object implements the SrcApiRoutersRiskStressTestResult interface.
 */
export function instanceOfSrcApiRoutersRiskStressTestResult(value: object): value is SrcApiRoutersRiskStressTestResult {
    return true;
}

export function SrcApiRoutersRiskStressTestResultFromJSON(json: any): SrcApiRoutersRiskStressTestResult {
    return SrcApiRoutersRiskStressTestResultFromJSONTyped(json, false);
}

export function SrcApiRoutersRiskStressTestResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SrcApiRoutersRiskStressTestResult {
    if (json == null) {
        return json;
    }
    return {
        
        'irr': json['irr'] == null ? undefined : json['irr'],
        'equityMultiple': json['equity_multiple'] == null ? undefined : json['equity_multiple'],
        'roi': json['roi'] == null ? undefined : json['roi'],
        'maxDrawdown': json['max_drawdown'] == null ? undefined : json['max_drawdown'],
        'var95': json['var_95'] == null ? undefined : json['var_95'],
        'impactPct': json['impact_pct'] == null ? undefined : json['impact_pct'],
    };
}

export function SrcApiRoutersRiskStressTestResultToJSON(json: any): SrcApiRoutersRiskStressTestResult {
    return SrcApiRoutersRiskStressTestResultToJSONTyped(json, false);
}

export function SrcApiRoutersRiskStressTestResultToJSONTyped(value?: SrcApiRoutersRiskStressTestResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'irr': value['irr'],
        'equity_multiple': value['equityMultiple'],
        'roi': value['roi'],
        'max_drawdown': value['maxDrawdown'],
        'var_95': value['var95'],
        'impact_pct': value['impactPct'],
    };
}

