/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Liquidity metrics model.
 * @export
 * @interface SrcApiRoutersFinanceLiquidityMetrics
 */
export interface SrcApiRoutersFinanceLiquidityMetrics {
    /**
     * Minimum cash reserve
     * @type {number}
     * @memberof SrcApiRoutersFinanceLiquidityMetrics
     */
    minCashReserve: number;
    /**
     * Maximum cash reserve
     * @type {number}
     * @memberof SrcApiRoutersFinanceLiquidityMetrics
     */
    maxCashReserve: number;
    /**
     * Average cash reserve
     * @type {number}
     * @memberof SrcApiRoutersFinanceLiquidityMetrics
     */
    avgCashReserve: number;
    /**
     * Number of periods with shortfall
     * @type {number}
     * @memberof SrcApiRoutersFinanceLiquidityMetrics
     */
    numShortfallPeriods: number;
    /**
     * Maximum shortfall
     * @type {number}
     * @memberof SrcApiRoutersFinanceLiquidityMetrics
     */
    maxShortfall: number;
}

/**
 * Check if a given object implements the SrcApiRoutersFinanceLiquidityMetrics interface.
 */
export function instanceOfSrcApiRoutersFinanceLiquidityMetrics(value: object): value is SrcApiRoutersFinanceLiquidityMetrics {
    if (!('minCashReserve' in value) || value['minCashReserve'] === undefined) return false;
    if (!('maxCashReserve' in value) || value['maxCashReserve'] === undefined) return false;
    if (!('avgCashReserve' in value) || value['avgCashReserve'] === undefined) return false;
    if (!('numShortfallPeriods' in value) || value['numShortfallPeriods'] === undefined) return false;
    if (!('maxShortfall' in value) || value['maxShortfall'] === undefined) return false;
    return true;
}

export function SrcApiRoutersFinanceLiquidityMetricsFromJSON(json: any): SrcApiRoutersFinanceLiquidityMetrics {
    return SrcApiRoutersFinanceLiquidityMetricsFromJSONTyped(json, false);
}

export function SrcApiRoutersFinanceLiquidityMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SrcApiRoutersFinanceLiquidityMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'minCashReserve': json['min_cash_reserve'],
        'maxCashReserve': json['max_cash_reserve'],
        'avgCashReserve': json['avg_cash_reserve'],
        'numShortfallPeriods': json['num_shortfall_periods'],
        'maxShortfall': json['max_shortfall'],
    };
}

export function SrcApiRoutersFinanceLiquidityMetricsToJSON(json: any): SrcApiRoutersFinanceLiquidityMetrics {
    return SrcApiRoutersFinanceLiquidityMetricsToJSONTyped(json, false);
}

export function SrcApiRoutersFinanceLiquidityMetricsToJSONTyped(value?: SrcApiRoutersFinanceLiquidityMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min_cash_reserve': value['minCashReserve'],
        'max_cash_reserve': value['maxCashReserve'],
        'avg_cash_reserve': value['avgCashReserve'],
        'num_shortfall_periods': value['numShortfallPeriods'],
        'max_shortfall': value['maxShortfall'],
    };
}

