/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReinvestmentVisualizationResponse } from './ReinvestmentVisualizationResponse';
import {
    ReinvestmentVisualizationResponseFromJSON,
    ReinvestmentVisualizationResponseFromJSONTyped,
    ReinvestmentVisualizationResponseToJSON,
    ReinvestmentVisualizationResponseToJSONTyped,
} from './ReinvestmentVisualizationResponse';
import type { ReinvestmentEventResponse } from './ReinvestmentEventResponse';
import {
    ReinvestmentEventResponseFromJSON,
    ReinvestmentEventResponseFromJSONTyped,
    ReinvestmentEventResponseToJSON,
    ReinvestmentEventResponseToJSONTyped,
} from './ReinvestmentEventResponse';
import type { ReinvestmentSummaryResponse } from './ReinvestmentSummaryResponse';
import {
    ReinvestmentSummaryResponseFromJSON,
    ReinvestmentSummaryResponseFromJSONTyped,
    ReinvestmentSummaryResponseToJSON,
    ReinvestmentSummaryResponseToJSONTyped,
} from './ReinvestmentSummaryResponse';

/**
 * Reinvestment response model.
 * @export
 * @interface SrcApiRoutersReinvestmentReinvestmentResponse
 */
export interface SrcApiRoutersReinvestmentReinvestmentResponse {
    /**
     * List of reinvestment events
     * @type {Array<ReinvestmentEventResponse>}
     * @memberof SrcApiRoutersReinvestmentReinvestmentResponse
     */
    events: Array<ReinvestmentEventResponse>;
    /**
     * Summary of reinvestment activity
     * @type {ReinvestmentSummaryResponse}
     * @memberof SrcApiRoutersReinvestmentReinvestmentResponse
     */
    summary: ReinvestmentSummaryResponse;
    /**
     * Visualization data
     * @type {ReinvestmentVisualizationResponse}
     * @memberof SrcApiRoutersReinvestmentReinvestmentResponse
     */
    visualization: ReinvestmentVisualizationResponse;
}

/**
 * Check if a given object implements the SrcApiRoutersReinvestmentReinvestmentResponse interface.
 */
export function instanceOfSrcApiRoutersReinvestmentReinvestmentResponse(value: object): value is SrcApiRoutersReinvestmentReinvestmentResponse {
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('visualization' in value) || value['visualization'] === undefined) return false;
    return true;
}

export function SrcApiRoutersReinvestmentReinvestmentResponseFromJSON(json: any): SrcApiRoutersReinvestmentReinvestmentResponse {
    return SrcApiRoutersReinvestmentReinvestmentResponseFromJSONTyped(json, false);
}

export function SrcApiRoutersReinvestmentReinvestmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SrcApiRoutersReinvestmentReinvestmentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(ReinvestmentEventResponseFromJSON)),
        'summary': ReinvestmentSummaryResponseFromJSON(json['summary']),
        'visualization': ReinvestmentVisualizationResponseFromJSON(json['visualization']),
    };
}

export function SrcApiRoutersReinvestmentReinvestmentResponseToJSON(json: any): SrcApiRoutersReinvestmentReinvestmentResponse {
    return SrcApiRoutersReinvestmentReinvestmentResponseToJSONTyped(json, false);
}

export function SrcApiRoutersReinvestmentReinvestmentResponseToJSONTyped(value?: SrcApiRoutersReinvestmentReinvestmentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'events': ((value['events'] as Array<any>).map(ReinvestmentEventResponseToJSON)),
        'summary': ReinvestmentSummaryResponseToJSON(value['summary']),
        'visualization': ReinvestmentVisualizationResponseToJSON(value['visualization']),
    };
}

