/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Leverage metrics model.
 * @export
 * @interface SrcApiRoutersRiskLeverageMetrics
 */
export interface SrcApiRoutersRiskLeverageMetrics {
    /**
     * NAV utilisation
     * @type {number}
     * @memberof SrcApiRoutersRiskLeverageMetrics
     */
    navUtilisation: number;
    /**
     * Interest coverage ratio
     * @type {number}
     * @memberof SrcApiRoutersRiskLeverageMetrics
     */
    interestCoverage: number;
    /**
     * VaR uplift from leverage
     * @type {object}
     * @memberof SrcApiRoutersRiskLeverageMetrics
     */
    varUplift: object;
}

/**
 * Check if a given object implements the SrcApiRoutersRiskLeverageMetrics interface.
 */
export function instanceOfSrcApiRoutersRiskLeverageMetrics(value: object): value is SrcApiRoutersRiskLeverageMetrics {
    if (!('navUtilisation' in value) || value['navUtilisation'] === undefined) return false;
    if (!('interestCoverage' in value) || value['interestCoverage'] === undefined) return false;
    if (!('varUplift' in value) || value['varUplift'] === undefined) return false;
    return true;
}

export function SrcApiRoutersRiskLeverageMetricsFromJSON(json: any): SrcApiRoutersRiskLeverageMetrics {
    return SrcApiRoutersRiskLeverageMetricsFromJSONTyped(json, false);
}

export function SrcApiRoutersRiskLeverageMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SrcApiRoutersRiskLeverageMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'navUtilisation': json['nav_utilisation'],
        'interestCoverage': json['interest_coverage'],
        'varUplift': json['var_uplift'],
    };
}

export function SrcApiRoutersRiskLeverageMetricsToJSON(json: any): SrcApiRoutersRiskLeverageMetrics {
    return SrcApiRoutersRiskLeverageMetricsToJSONTyped(json, false);
}

export function SrcApiRoutersRiskLeverageMetricsToJSONTyped(value?: SrcApiRoutersRiskLeverageMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nav_utilisation': value['navUtilisation'],
        'interest_coverage': value['interestCoverage'],
        'var_uplift': value['varUplift'],
    };
}

