/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Model for stakeholder allocation data.
 * @export
 * @interface StakeholderAllocationModel
 */
export interface StakeholderAllocationModel {
    /**
     * Stakeholder name
     * @type {string}
     * @memberof StakeholderAllocationModel
     */
    stakeholder: string;
    /**
     * Amount allocated
     * @type {number}
     * @memberof StakeholderAllocationModel
     */
    amount: number;
    /**
     * Percentage of total distribution
     * @type {number}
     * @memberof StakeholderAllocationModel
     */
    percentage: number;
}

/**
 * Check if a given object implements the StakeholderAllocationModel interface.
 */
export function instanceOfStakeholderAllocationModel(value: object): value is StakeholderAllocationModel {
    if (!('stakeholder' in value) || value['stakeholder'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('percentage' in value) || value['percentage'] === undefined) return false;
    return true;
}

export function StakeholderAllocationModelFromJSON(json: any): StakeholderAllocationModel {
    return StakeholderAllocationModelFromJSONTyped(json, false);
}

export function StakeholderAllocationModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): StakeholderAllocationModel {
    if (json == null) {
        return json;
    }
    return {
        
        'stakeholder': json['stakeholder'],
        'amount': json['amount'],
        'percentage': json['percentage'],
    };
}

export function StakeholderAllocationModelToJSON(json: any): StakeholderAllocationModel {
    return StakeholderAllocationModelToJSONTyped(json, false);
}

export function StakeholderAllocationModelToJSONTyped(value?: StakeholderAllocationModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stakeholder': value['stakeholder'],
        'amount': value['amount'],
        'percentage': value['percentage'],
    };
}

