/* tslint:disable */
/* eslint-disable */
/**
 * EQU IHOME SIM ENGINE API
 * API for running home equity investment fund simulations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@equihome.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Model for waterfall tier data.
 * @export
 * @interface WaterfallTierModel
 */
export interface WaterfallTierModel {
    /**
     * Tier name
     * @type {string}
     * @memberof WaterfallTierModel
     */
    tier: string;
    /**
     * Amount allocated to this tier
     * @type {number}
     * @memberof WaterfallTierModel
     */
    amount: number;
    /**
     * Percentage of total distribution
     * @type {number}
     * @memberof WaterfallTierModel
     */
    percentage: number;
}

/**
 * Check if a given object implements the WaterfallTierModel interface.
 */
export function instanceOfWaterfallTierModel(value: object): value is WaterfallTierModel {
    if (!('tier' in value) || value['tier'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('percentage' in value) || value['percentage'] === undefined) return false;
    return true;
}

export function WaterfallTierModelFromJSON(json: any): WaterfallTierModel {
    return WaterfallTierModelFromJSONTyped(json, false);
}

export function WaterfallTierModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaterfallTierModel {
    if (json == null) {
        return json;
    }
    return {
        
        'tier': json['tier'],
        'amount': json['amount'],
        'percentage': json['percentage'],
    };
}

export function WaterfallTierModelToJSON(json: any): WaterfallTierModel {
    return WaterfallTierModelToJSONTyped(json, false);
}

export function WaterfallTierModelToJSONTyped(value?: WaterfallTierModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tier': value['tier'],
        'amount': value['amount'],
        'percentage': value['percentage'],
    };
}

